[package]
org = "fiducia.cloud"
name = "fiducia-clients-julia"
version = "0.1.0"
description = "julia client for fiducia-clients"
license = "MIT"

[package.repository]
vcs = "git"
url = "https://github.com/fiducia.cloud/fiducia-clients"

[publish]
exclude = []
