#!/usr/bin/env python3
"""Generate fiducia client libraries from operations.json — the single source of
truth for the HTTP surface. Edit the manifest, run `python3 generate.py`, and
every client is regenerated identically; they can't drift from each other or the
server. Each generated client is a thin, dependency-free HTTP wrapper that
returns parsed JSON.

    python3 generate.py            # regenerate all supported languages
    python3 generate.py python go  # just these
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
MANIFEST = json.load(open(os.path.join(ROOT, "operations.json")))
OPS = MANIFEST["operations"]
BANNER_PY = "# GENERATED by generate.py from operations.json — DO NOT EDIT BY HAND."
BANNER_C = "// GENERATED by generate.py from operations.json — DO NOT EDIT BY HAND."


def pascal(s):
    return "".join(w[:1].upper() + w[1:] for w in s.split("_"))


def camel(s):
    p = pascal(s)
    return p[:1].lower() + p[1:]


def parts(op):
    p = op["params"]
    return ([x for x in p if x["in"] == "path"],
            [x for x in p if x["in"] == "query"],
            [x for x in p if x["in"] == "body"],
            [x for x in p if not x.get("optional")],
            [x for x in p if x.get("optional")])


# --------------------------------------------------------------------------- py
PY_PRE = '''"""Fiducia client (Python) — generated. Zero deps (stdlib urllib).

    c = FiduciaClient("https://api.fiducia.cloud")
    g = c.lock_acquire_many(["a", "b"], holder="w1", ttl_ms=30000)
    c.lock_release("w1", g["result"]["output"]["fencing_token"])
"""
import json as _json
import urllib.error
import urllib.parse
import urllib.request


class FiduciaError(Exception):
    def __init__(self, status, body):
        super().__init__("fiducia: HTTP %s" % status)
        self.status, self.body = status, body


def _enc(s):
    return urllib.parse.quote(str(s), safe="")


class FiduciaClient:
    def __init__(self, base_url, timeout=30):
        self.base, self.timeout = base_url.rstrip("/"), timeout

    def _request(self, method, path, body=None):
        data = _json.dumps(body).encode() if body is not None else None
        req = urllib.request.Request(self.base + path, data=data, method=method)
        if data is not None:
            req.add_header("content-type", "application/json")
        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as r:
                text = r.read().decode()
                return _json.loads(text) if text else None
        except urllib.error.HTTPError as e:
            text = e.read().decode()
            raise FiduciaError(e.code, _json.loads(text) if text else None)
'''


def emit_python(op):
    pp, qp, bp, req, opt = parts(op)
    args = ["self"] + [x["name"] for x in req] + ["%s=None" % x["name"] for x in opt]
    path = '"%s"' % op["path"].replace("{", "%s<<").replace("}", ">>")
    # build path expression
    fmt = op["path"]
    enc_args = []
    for x in pp:
        fmt = fmt.replace("{%s}" % x["name"], "%s")
        enc_args.append("_enc(%s)" % x["name"])
    for x in qp:
        fmt += ("&" if "?" in fmt else "?") + x["name"] + "=%s"
        enc_args.append("_enc(%s)" % x["name"])
    pathexpr = '"%s"' % fmt + ((" %% (%s)" % ", ".join(enc_args)) if len(enc_args) > 1
                               else (" %% %s" % enc_args[0]) if enc_args else "")
    call = '"%s", %s' % (op["method"], pathexpr)
    if bp:
        body = "{%s}" % ", ".join('"%s": %s' % (x["name"], x["name"]) for x in bp)
        call += ", %s" % body
    doc = op.get("doc", "")
    return ('    def %s(%s):\n        """%s"""\n        return self._request(%s)\n'
            % (op["name"], ", ".join(args), doc, call))


def gen_python():
    body = PY_PRE + "\n" + "\n".join(emit_python(op) for op in OPS)
    return body.replace('"""Fiducia client (Python) — generated. Zero deps (stdlib urllib).',
                        BANNER_PY + '\n"""Fiducia client (Python) — generated. Zero deps (stdlib urllib).')


# --------------------------------------------------------------------------- ts
TS_PRE = BANNER_C + '''
// Fiducia client (TypeScript) — generated. Zero runtime deps (global fetch).
export class FiduciaError extends Error {
  constructor(public status: number, public body: any) { super(`fiducia: HTTP ${status}`); }
}
const enc = encodeURIComponent;
export class FiduciaClient {
  constructor(private base: string, private timeout = 30000) { this.base = base.replace(/\\/$/, ""); }
  private async request(method: string, path: string, body?: any): Promise<any> {
    const ctl = new AbortController();
    const t = setTimeout(() => ctl.abort(), this.timeout);
    try {
      const r = await fetch(this.base + path, {
        method, signal: ctl.signal,
        headers: body !== undefined ? { "content-type": "application/json" } : {},
        body: body !== undefined ? JSON.stringify(body) : undefined,
      });
      const text = await r.text();
      const parsed = text ? JSON.parse(text) : null;
      if (!r.ok) throw new FiduciaError(r.status, parsed);
      return parsed;
    } finally { clearTimeout(t); }
  }
'''


def ts_type(t):
    return {"string": "string", "int": "number", "number": "number", "bool": "boolean",
            "string[]": "string[]", "object": "Record<string, any>"}[t]


def emit_ts(op):
    pp, qp, bp, req, opt = parts(op)
    sig = [("%s: %s" % (camel(x["name"]), ts_type(x["type"]))) for x in req]
    if opt:
        fields = "; ".join("%s?: %s" % (x["name"], ts_type(x["type"])) for x in opt)
        sig.append("opts: { %s } = {}" % fields)
    # path
    fmt = op["path"]
    for x in pp:
        fmt = fmt.replace("{%s}" % x["name"], "${enc(%s)}" % camel(x["name"]))
    for x in qp:
        fmt += ("&" if "?" in fmt else "?") + x["name"] + "=${enc(%s)}" % camel(x["name"])
    call = '"%s", `%s`' % (op["method"], fmt)
    if bp:
        items = []
        for x in bp:
            src = camel(x["name"]) if not x.get("optional") else "opts.%s" % x["name"]
            items.append("%s: %s" % (x["name"], src))
        call += ", { %s }" % ", ".join(items)
    return ("  async %s(%s): Promise<any> {\n    return this.request(%s);\n  }\n"
            % (camel(op["name"]), ", ".join(sig), call))


def gen_ts():
    return TS_PRE + "\n" + "\n".join(emit_ts(op) for op in OPS) + "}\n"


# --------------------------------------------------------------------------- go
GO_PRE = BANNER_C + '''
// Package fiducia is a generated, zero-dependency HTTP client (stdlib net/http).
package fiducia

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
)

type Error struct {
	Status int
	Body   map[string]any
}

func (e *Error) Error() string { return fmt.Sprintf("fiducia: HTTP %d", e.Status) }

type Client struct {
	Base string
	HTTP *http.Client
}

func New(base string) *Client { return &Client{Base: base, HTTP: http.DefaultClient} }

func enc(s string) string { return url.QueryEscape(s) }

func merge(dst, src map[string]any) map[string]any {
	for k, v := range src {
		dst[k] = v
	}
	return dst
}

func (c *Client) request(method, path string, body map[string]any) (map[string]any, error) {
	var rdr io.Reader
	if body != nil {
		b, _ := json.Marshal(body)
		rdr = bytes.NewReader(b)
	}
	req, err := http.NewRequest(method, c.Base+path, rdr)
	if err != nil {
		return nil, err
	}
	if body != nil {
		req.Header.Set("content-type", "application/json")
	}
	resp, err := c.HTTP.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(resp.Body)
	var out map[string]any
	if len(raw) > 0 {
		_ = json.Unmarshal(raw, &out)
	}
	if resp.StatusCode >= 400 {
		return nil, &Error{Status: resp.StatusCode, Body: out}
	}
	return out, nil
}
'''


def go_type(t):
    return {"string": "string", "int": "int64", "number": "float64", "bool": "bool",
            "string[]": "[]string", "object": "map[string]any"}[t]


def emit_go(op):
    pp, qp, bp, req, opt = parts(op)
    sig = [("%s %s" % (camel(x["name"]), go_type(x["type"]))) for x in req]
    if opt:
        sig.append("opts map[string]any")
    lines = []
    # path
    fmt = op["path"]
    enc_args = []
    for x in pp:
        fmt = fmt.replace("{%s}" % x["name"], "%s")
        enc_args.append("enc(%s)" % camel(x["name"]))
    for x in qp:
        fmt += ("&" if "?" in fmt else "?") + x["name"] + "=%s"
        enc_args.append("enc(%s)" % camel(x["name"]))
    if enc_args:
        lines.append('\tpath := fmt.Sprintf("%s", %s)' % (fmt, ", ".join(enc_args)))
        pathvar = "path"
    else:
        pathvar = '"%s"' % fmt
    req_body = [x for x in bp if not x.get("optional")]
    if bp:
        inits = ", ".join('"%s": %s' % (x["name"], camel(x["name"])) for x in req_body)
        lines.append("\tbody := map[string]any{%s}" % inits)
        if opt:
            lines.append("\tmerge(body, opts)")
        bodyvar = "body"
    else:
        bodyvar = "nil"
    lines.append('\treturn c.request("%s", %s, %s)' % (op["method"], pathvar, bodyvar))
    return ("// %s %s\nfunc (c *Client) %s(%s) (map[string]any, error) {\n%s\n}\n"
            % (pascal(op["name"]), op.get("doc", ""), pascal(op["name"]),
               ", ".join(sig), "\n".join(lines)))


def gen_go():
    return GO_PRE + "\n" + "\n".join(emit_go(op) for op in OPS)


TARGETS = {
    "python": ("clients/python/fiducia.py", gen_python),
    "ts": ("clients/ts/fiducia.ts", gen_ts),
    "go": ("clients/go/fiducia.go", gen_go),
}


def main():
    want = sys.argv[1:] or list(TARGETS)
    for lang in want:
        rel, gen = TARGETS[lang]
        path = os.path.join(ROOT, rel)
        open(path, "w").write(gen())
        print("generated %-8s -> %s (%d ops)" % (lang, rel, len(OPS)))


if __name__ == "__main__":
    main()
