#!/usr/bin/env python3
"""Generate fiducia client libraries from operations.json — the single source of
truth for the HTTP surface. Edit the manifest, run `python3 generate.py`, and
every client is regenerated identically; they can't drift from each other or the
server. Each generated client is a thin, dependency-free HTTP wrapper that
returns parsed JSON.

    python3 generate.py            # regenerate all supported languages
    python3 generate.py python go  # just these
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
MANIFEST = json.load(open(os.path.join(ROOT, "operations.json")))
OPS = MANIFEST["operations"]
BANNER_PY = "# GENERATED by generate.py from operations.json — DO NOT EDIT BY HAND."
BANNER_C = "// GENERATED by generate.py from operations.json — DO NOT EDIT BY HAND."


def pascal(s):
    return "".join(w[:1].upper() + w[1:] for w in s.split("_"))


def camel(s):
    p = pascal(s)
    return p[:1].lower() + p[1:]


def parts(op):
    p = op["params"]
    return ([x for x in p if x["in"] == "path"],
            [x for x in p if x["in"] == "query"],
            [x for x in p if x["in"] == "body"],
            [x for x in p if not x.get("optional")],
            [x for x in p if x.get("optional")])


# --------------------------------------------------------------------------- py
PY_PRE = '''"""Fiducia client (Python) — generated. Zero deps (stdlib urllib).

    c = FiduciaClient("https://api.fiducia.cloud")
    g = c.lock_acquire_many(["a", "b"], holder="w1", ttl_ms=30000)
    c.lock_release("w1", g["result"]["output"]["fencing_token"])
"""
import json as _json
import urllib.error
import urllib.parse
import urllib.request


class FiduciaError(Exception):
    def __init__(self, status, body):
        super().__init__("fiducia: HTTP %s" % status)
        self.status, self.body = status, body


def _enc(s):
    return urllib.parse.quote(str(s), safe="")


class FiduciaClient:
    def __init__(self, base_url, timeout=30):
        self.base, self.timeout = base_url.rstrip("/"), timeout

    def _request(self, method, path, body=None):
        data = _json.dumps(body).encode() if body is not None else None
        req = urllib.request.Request(self.base + path, data=data, method=method)
        if data is not None:
            req.add_header("content-type", "application/json")
        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as r:
                text = r.read().decode()
                return _json.loads(text) if text else None
        except urllib.error.HTTPError as e:
            text = e.read().decode()
            raise FiduciaError(e.code, _json.loads(text) if text else None)
'''


def emit_python(op):
    pp, qp, bp, req, opt = parts(op)
    args = ["self"] + [x["name"] for x in req] + ["%s=None" % x["name"] for x in opt]
    path = '"%s"' % op["path"].replace("{", "%s<<").replace("}", ">>")
    # build path expression
    fmt = op["path"]
    enc_args = []
    for x in pp:
        fmt = fmt.replace("{%s}" % x["name"], "%s")
        enc_args.append("_enc(%s)" % x["name"])
    for x in qp:
        fmt += ("&" if "?" in fmt else "?") + x["name"] + "=%s"
        enc_args.append("_enc(%s)" % x["name"])
    pathexpr = '"%s"' % fmt + ((" %% (%s)" % ", ".join(enc_args)) if len(enc_args) > 1
                               else (" %% %s" % enc_args[0]) if enc_args else "")
    call = '"%s", %s' % (op["method"], pathexpr)
    if bp:
        body = "{%s}" % ", ".join('"%s": %s' % (x["name"], x["name"]) for x in bp)
        call += ", %s" % body
    doc = op.get("doc", "")
    return ('    def %s(%s):\n        """%s"""\n        return self._request(%s)\n'
            % (op["name"], ", ".join(args), doc, call))


def gen_python():
    body = PY_PRE + "\n" + "\n".join(emit_python(op) for op in OPS)
    return body.replace('"""Fiducia client (Python) — generated. Zero deps (stdlib urllib).',
                        BANNER_PY + '\n"""Fiducia client (Python) — generated. Zero deps (stdlib urllib).')


# --------------------------------------------------------------------------- ts
TS_PRE = BANNER_C + '''
// Fiducia client (TypeScript) — generated. Zero runtime deps (global fetch).
export class FiduciaError extends Error {
  constructor(public status: number, public body: any) { super(`fiducia: HTTP ${status}`); }
}
const enc = encodeURIComponent;
export class FiduciaClient {
  constructor(private base: string, private timeout = 30000) { this.base = base.replace(/\\/$/, ""); }
  private async request(method: string, path: string, body?: any): Promise<any> {
    const ctl = new AbortController();
    const t = setTimeout(() => ctl.abort(), this.timeout);
    try {
      const r = await fetch(this.base + path, {
        method, signal: ctl.signal,
        headers: body !== undefined ? { "content-type": "application/json" } : {},
        body: body !== undefined ? JSON.stringify(body) : undefined,
      });
      const text = await r.text();
      const parsed = text ? JSON.parse(text) : null;
      if (!r.ok) throw new FiduciaError(r.status, parsed);
      return parsed;
    } finally { clearTimeout(t); }
  }
'''


def ts_type(t):
    return {"string": "string", "int": "number", "number": "number", "bool": "boolean",
            "string[]": "string[]", "object": "Record<string, any>"}[t]


def emit_ts(op):
    pp, qp, bp, req, opt = parts(op)
    sig = [("%s: %s" % (camel(x["name"]), ts_type(x["type"]))) for x in req]
    if opt:
        fields = "; ".join("%s?: %s" % (x["name"], ts_type(x["type"])) for x in opt)
        sig.append("opts: { %s } = {}" % fields)
    # path
    fmt = op["path"]
    for x in pp:
        fmt = fmt.replace("{%s}" % x["name"], "${enc(%s)}" % camel(x["name"]))
    for x in qp:
        fmt += ("&" if "?" in fmt else "?") + x["name"] + "=${enc(%s)}" % camel(x["name"])
    call = '"%s", `%s`' % (op["method"], fmt)
    if bp:
        items = []
        for x in bp:
            src = camel(x["name"]) if not x.get("optional") else "opts.%s" % x["name"]
            items.append("%s: %s" % (x["name"], src))
        call += ", { %s }" % ", ".join(items)
    return ("  async %s(%s): Promise<any> {\n    return this.request(%s);\n  }\n"
            % (camel(op["name"]), ", ".join(sig), call))


def gen_ts():
    return TS_PRE + "\n" + "\n".join(emit_ts(op) for op in OPS) + "}\n"


# --------------------------------------------------------------------------- go
GO_PRE = BANNER_C + '''
// Package fiducia is a generated, zero-dependency HTTP client (stdlib net/http).
package fiducia

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
)

type Error struct {
	Status int
	Body   map[string]any
}

func (e *Error) Error() string { return fmt.Sprintf("fiducia: HTTP %d", e.Status) }

type Client struct {
	Base string
	HTTP *http.Client
}

func New(base string) *Client { return &Client{Base: base, HTTP: http.DefaultClient} }

func enc(s string) string { return url.QueryEscape(s) }

func merge(dst, src map[string]any) map[string]any {
	for k, v := range src {
		dst[k] = v
	}
	return dst
}

func (c *Client) request(method, path string, body map[string]any) (map[string]any, error) {
	var rdr io.Reader
	if body != nil {
		b, _ := json.Marshal(body)
		rdr = bytes.NewReader(b)
	}
	req, err := http.NewRequest(method, c.Base+path, rdr)
	if err != nil {
		return nil, err
	}
	if body != nil {
		req.Header.Set("content-type", "application/json")
	}
	resp, err := c.HTTP.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(resp.Body)
	var out map[string]any
	if len(raw) > 0 {
		_ = json.Unmarshal(raw, &out)
	}
	if resp.StatusCode >= 400 {
		return nil, &Error{Status: resp.StatusCode, Body: out}
	}
	return out, nil
}
'''


def go_type(t):
    return {"string": "string", "int": "int64", "number": "float64", "bool": "bool",
            "string[]": "[]string", "object": "map[string]any"}[t]


def emit_go(op):
    pp, qp, bp, req, opt = parts(op)
    sig = [("%s %s" % (camel(x["name"]), go_type(x["type"]))) for x in req]
    if opt:
        sig.append("opts map[string]any")
    lines = []
    # path
    fmt = op["path"]
    enc_args = []
    for x in pp:
        fmt = fmt.replace("{%s}" % x["name"], "%s")
        enc_args.append("enc(%s)" % camel(x["name"]))
    for x in qp:
        fmt += ("&" if "?" in fmt else "?") + x["name"] + "=%s"
        enc_args.append("enc(%s)" % camel(x["name"]))
    if enc_args:
        lines.append('\tpath := fmt.Sprintf("%s", %s)' % (fmt, ", ".join(enc_args)))
        pathvar = "path"
    else:
        pathvar = '"%s"' % fmt
    req_body = [x for x in bp if not x.get("optional")]
    if bp:
        inits = ", ".join('"%s": %s' % (x["name"], camel(x["name"])) for x in req_body)
        lines.append("\tbody := map[string]any{%s}" % inits)
        if opt:
            lines.append("\tmerge(body, opts)")
        bodyvar = "body"
    else:
        bodyvar = "nil"
    lines.append('\treturn c.request("%s", %s, %s)' % (op["method"], pathvar, bodyvar))
    return ("// %s %s\nfunc (c *Client) %s(%s) (map[string]any, error) {\n%s\n}\n"
            % (pascal(op["name"]), op.get("doc", ""), pascal(op["name"]),
               ", ".join(sig), "\n".join(lines)))


def gen_go():
    return GO_PRE + "\n" + "\n".join(emit_go(op) for op in OPS)


# ------------------------------------------------------------------- rust-wasm
# A Rust client compiled to WebAssembly. Unlike clients/rust (blocking `ureq`),
# the wasm build cannot open sockets, so its transport is the browser `fetch`
# API via wasm-bindgen. Every op is an async method; wasm-bindgen exports the
# snake_case names to JS as camelCase. Kept separate from clients/rust so that
# native client stays a plain blocking crate.
RUST_WASM_PRE = BANNER_C + '''
//! Fiducia client (Rust -> WebAssembly) — generated. Browser transport via `fetch`.
//!
//! Build:  wasm-pack build clients/rust-wasm --target web
//!
//! Every operation is an `async` method (exported to JS as camelCase) that
//! resolves to the parsed JSON response, or rejects with `{ status, body }` on a
//! non-2xx response or transport failure.
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use wasm_bindgen_futures::JsFuture;
use web_sys::{Request, RequestInit, Response};

/// URL-encode a path/query segment via the JS `encodeURIComponent`.
fn enc(s: &str) -> String {
    String::from(js_sys::encode_uri_component(s))
}

/// Build the `{ status, body }` rejection value used for every failure.
fn err(status: u16, body: JsValue) -> JsValue {
    let o = js_sys::Object::new();
    let _ = js_sys::Reflect::set(&o, &JsValue::from_str("status"), &JsValue::from(status));
    let _ = js_sys::Reflect::set(&o, &JsValue::from_str("body"), &body);
    o.into()
}

#[wasm_bindgen]
pub struct FiduciaClient {
    base: String,
}

#[wasm_bindgen]
impl FiduciaClient {
    #[wasm_bindgen(constructor)]
    pub fn new(base_url: &str) -> FiduciaClient {
        FiduciaClient { base: base_url.trim_end_matches('/').to_string() }
    }

    async fn request(&self, method: &str, path: String, body: Option<String>) -> Result<JsValue, JsValue> {
        let opts = RequestInit::new();
        opts.set_method(method);
        if let Some(ref b) = body {
            opts.set_body(&JsValue::from_str(b));
        }
        let url = format!("{}{}", self.base, path);
        let request = Request::new_with_str_and_init(&url, &opts).map_err(|e| err(0, e))?;
        if body.is_some() {
            request.headers().set("content-type", "application/json").map_err(|e| err(0, e))?;
        }
        let window = web_sys::window().ok_or_else(|| err(0, JsValue::from_str("no global `window`")))?;
        let resp_value = JsFuture::from(window.fetch_with_request(&request)).await.map_err(|e| err(0, e))?;
        let resp: Response = resp_value.dyn_into().map_err(|e| err(0, e))?;
        let text_value = JsFuture::from(resp.text().map_err(|e| err(0, e))?).await.map_err(|e| err(0, e))?;
        let text = text_value.as_string().unwrap_or_default();
        let parsed = if text.is_empty() {
            JsValue::NULL
        } else {
            js_sys::JSON::parse(&text).unwrap_or(JsValue::NULL)
        };
        if !resp.ok() {
            return Err(err(resp.status(), parsed));
        }
        Ok(parsed)
    }
'''

# `int` maps to f64 (JS `number`), not i64: wasm-bindgen would expose i64 as a JS
# `bigint`, which mismatches the response JSON (numbers) and the sibling TS
# client. Integer-valued params are re-cast to i64 when building the JSON body so
# the wire form stays a clean integer (e.g. 30000, never 30000.0).
RUST_WASM_TYPE = {"string": "String", "int": "f64", "number": "f64", "bool": "bool",
                  "string[]": "Vec<String>", "object": "JsValue"}

_RW_OBJ_TO_STR = "js_sys::JSON::stringify(&%s).ok().and_then(|s| s.as_string()).unwrap_or_default()"


def _rw_scalar_enc(typ, var):
    # A scalar path/query value, encoded for a URL.
    if typ == "string":
        return "enc(&%s)" % var
    if typ == "int":
        return "enc(&(%s as i64).to_string())" % var
    return "enc(&%s.to_string())" % var


def _rw_json_scalar(typ, var):
    # A scalar body value as a serde_json::Value. Integers cast back to i64 so the
    # JSON is an integer rather than a float.
    if typ == "int":
        return "serde_json::json!(%s as i64)" % var
    return "serde_json::json!(%s)" % var


def _rw_query_lines(x):
    # Code that appends one query param to `_q` (optional ones only when present).
    name = x["name"]
    if x["type"] == "object":
        val = "enc(&%s)" % (_RW_OBJ_TO_STR % name)
    else:
        val = _rw_scalar_enc(x["type"], name)
    push = '        _q.push(format!("%s={}", %s));' % (name, val)
    if not x.get("optional"):
        return [push]
    if x["type"] == "object":
        return ["        if !%s.is_null() && !%s.is_undefined() {" % (name, name),
                "    " + push, "        }"]
    val = _rw_scalar_enc(x["type"], "v")
    return ["        if let Some(v) = %s {" % name,
            '            _q.push(format!("%s={}", %s));' % (name, val),
            "        }"]


def _rw_body_value(x):
    # A required body param -> serde_json::Value expression.
    if x["type"] == "object":
        return "serde_wasm_bindgen::from_value(%s).map_err(|e| err(0, e.into()))?" % x["name"]
    if x["type"] == "string":
        return "serde_json::Value::String(%s)" % x["name"]
    return _rw_json_scalar(x["type"], x["name"])


def emit_rust_wasm(op):
    pp, qp, bp, req, opt = parts(op)
    sig = ["&self"]
    for x in req:
        sig.append("%s: %s" % (x["name"], RUST_WASM_TYPE[x["type"]]))
    for x in opt:
        # Optional objects stay a nullable JsValue; other optionals are Option<T>.
        if x["type"] == "object":
            sig.append("%s: JsValue" % x["name"])
        else:
            sig.append("%s: Option<%s>" % (x["name"], RUST_WASM_TYPE[x["type"]]))
    lines = []
    # path (path params only; query is appended below so optionals can be omitted)
    fmt = op["path"]
    penc = []
    for x in pp:
        fmt = fmt.replace("{%s}" % x["name"], "{}")
        penc.append(_rw_scalar_enc(x["type"], x["name"]))
    decl = "let mut path" if qp else "let path"
    if penc:
        lines.append('        %s = format!("%s", %s);' % (decl, fmt, ", ".join(penc)))
    else:
        lines.append('        %s = String::from("%s");' % (decl, fmt))
    # query string (required always, optional only when provided)
    if qp:
        lines.append("        let mut _q: Vec<String> = Vec::new();")
        for x in qp:
            lines.extend(_rw_query_lines(x))
        lines.append("        if !_q.is_empty() {")
        lines.append("            path.push('?');")
        lines.append('            path.push_str(&_q.join("&"));')
        lines.append("        }")
    # body map
    if bp:
        lines.append("        let mut _body = serde_json::Map::new();")
        for x in bp:
            if not x.get("optional"):
                lines.append('        _body.insert("%s".to_string(), %s);' % (x["name"], _rw_body_value(x)))
            elif x["type"] == "object":
                lines.append("        if !%s.is_null() && !%s.is_undefined() {" % (x["name"], x["name"]))
                lines.append('            _body.insert("%s".to_string(), serde_wasm_bindgen::from_value(%s).map_err(|e| err(0, e.into()))?);'
                             % (x["name"], x["name"]))
                lines.append("        }")
            else:
                lines.append("        if let Some(v) = %s {" % x["name"])
                lines.append('            _body.insert("%s".to_string(), %s);' % (x["name"], _rw_json_scalar(x["type"], "v")))
                lines.append("        }")
        lines.append("        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();")
        bodyarg = "Some(_payload)"
    else:
        bodyarg = "None"
    lines.append('        self.request("%s", path, %s).await' % (op["method"], bodyarg))
    doc = op.get("doc", "")
    # Export camelCase JS names to match the TypeScript client's surface.
    return ('    /// %s\n    #[wasm_bindgen(js_name = %s)]\n    pub async fn %s(%s) -> Result<JsValue, JsValue> {\n%s\n    }\n'
            % (doc, camel(op["name"]), op["name"], ", ".join(sig), "\n".join(lines)))


def gen_rust_wasm():
    return RUST_WASM_PRE + "\n" + "\n".join(emit_rust_wasm(op) for op in OPS) + "}\n"


# ------------------------------------------------------------------------- docs
def gen_markdown():
    rows = ["<!-- GENERATED by generate.py from operations.json — DO NOT EDIT BY HAND. -->",
            "# Fiducia HTTP endpoint reference",
            "",
            "Every client in `clients/` is generated from `operations.json`; this table is",
            "too. `?param` marks an optional argument.",
            "",
            "| Method | Path | Args | Description |",
            "|--------|------|------|-------------|"]
    for op in OPS:
        args = ", ".join("`%s`%s" % (p["name"], "?" if p.get("optional") else "") for p in op["params"])
        rows.append("| `%s` | `%s` | %s | %s |" % (op["method"], op["path"], args or "—", op.get("doc", "")))
    return "\n".join(rows) + "\n"


TARGETS = {
    "python": ("clients/python/fiducia.py", gen_python),
    "ts": ("clients/ts/fiducia.ts", gen_ts),
    "go": ("clients/go/fiducia.go", gen_go),
    "rust-wasm": ("clients/rust-wasm/src/lib.rs", gen_rust_wasm),
    "docs": ("ENDPOINTS.md", gen_markdown),
}


def main():
    want = sys.argv[1:] or list(TARGETS)
    for lang in want:
        rel, gen = TARGETS[lang]
        path = os.path.join(ROOT, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        open(path, "w").write(gen())
        print("generated %-8s -> %s (%d ops)" % (lang, rel, len(OPS)))


if __name__ == "__main__":
    main()
