#!/usr/bin/env python3
"""Generate Fiducia clients from the shared operations manifest.

operations.json owns the HTTP surface. First-tier clients combine reviewed
language templates with generated manifest operations; Rust-Wasm and the endpoint
reference are emitted directly. `--check` verifies every committed target.

    python3 generate.py            # regenerate all supported languages
    python3 generate.py python go  # just these
"""
import json
import keyword
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
MANIFEST = json.load(open(os.path.join(ROOT, "operations.json")))
OPS = MANIFEST["operations"]
BANNER_PY = "# GENERATED by generate.py from operations.json — DO NOT EDIT BY HAND."
BANNER_C = "// GENERATED by generate.py from operations.json — DO NOT EDIT BY HAND."
TEMPLATE_DIR = os.path.join(ROOT, "templates")

# The first-tier clients intentionally expose a richer, language-idiomatic API
# for the long-standing coordination primitives. Their production transport and
# helper behavior lives in reviewed templates; operations added later are
# emitted from operations.json into an explicit marker. Keeping this list next
# to the emitters makes the split auditable and prevents a manifest regeneration
# from replacing the richer clients with a thin baseline again.
RICH_OPERATION_NAMES = {
    "health", "status",
    "lock_get", "lock_acquire", "lock_acquire_many", "lock_release",
    "semaphore_get", "semaphore_acquire", "semaphore_release",
    "idempotency_get", "idempotency_claim", "idempotency_complete",
    "kv_get", "kv_put", "kv_delete",
    "election_get", "election_campaign", "election_renew", "election_resign",
    "service_instances", "service_register", "service_heartbeat", "service_deregister",
    "rate_limit_get", "rate_limit_check",
    "schedule_get", "schedule_upsert", "schedule_record_run", "schedule_history",
}
GENERATED_FIRST_TIER_OPS = [op for op in OPS if op["name"] not in RICH_OPERATION_NAMES]


def template(name):
    path = os.path.join(TEMPLATE_DIR, name)
    with open(path, encoding="utf-8") as src:
        content = src.read()
    marker = "{{GENERATED_OPERATIONS}}"
    if content.count(marker) != 1:
        raise ValueError("template %s must contain exactly one %s marker" % (name, marker))
    return content


def pascal(s):
    return "".join(w[:1].upper() + w[1:] for w in s.split("_"))


def camel(s):
    p = pascal(s)
    return p[:1].lower() + p[1:]


def parts(op):
    p = op["params"]
    return ([x for x in p if x["in"] == "path"],
            [x for x in p if x["in"] == "query"],
            [x for x in p if x["in"] == "body"],
            [x for x in p if not x.get("optional")],
            [x for x in p if x.get("optional")])


# --------------------------------------------------------------------------- py
def py_ident(name):
    """Return a valid Python identifier while preserving the wire field name."""
    return name + "_" if keyword.iskeyword(name) else name


def emit_python(op):
    pp, qp, bp, req, opt = parts(op)
    args = ["self"]
    args.extend(py_ident(x["name"]) for x in req)
    args.extend("%s=None" % py_ident(x["name"]) for x in opt)
    args.append("**request_opts")

    fmt = op["path"]
    enc_args = []
    for x in pp:
        fmt = fmt.replace("{%s}" % x["name"], "%s")
        enc_args.append("_enc(%s)" % py_ident(x["name"]))
    path_expr = '"%s"' % fmt
    if len(enc_args) > 1:
        path_expr += " % (%s)" % ", ".join(enc_args)
    elif enc_args:
        path_expr += " % %s" % enc_args[0]

    scalar_query = [x for x in qp if x["type"] != "object"]
    object_query = [x for x in qp if x["type"] == "object"]
    if scalar_query or object_query:
        query_args = ["%s=%s" % (x["name"], py_ident(x["name"])) for x in scalar_query]
        query_args.extend("**_metadata_query(%s)" % py_ident(x["name"]) for x in object_query)
        path_expr = "_query(%s, %s)" % (path_expr, ", ".join(query_args))

    call_args = ['"%s"' % op["method"], path_expr]
    if bp:
        body = "{%s}" % ", ".join(
            '"%s": %s' % (x["name"], py_ident(x["name"])) for x in bp
        )
        call_args.append(body)
    call_args.append("**request_opts")
    doc = op.get("doc", "")
    return ('    def %s(%s):\n        """%s"""\n        return self._request(%s)\n'
            % (op["name"], ", ".join(args), doc, ", ".join(call_args)))


def gen_python():
    generated = "\n".join(emit_python(op) for op in GENERATED_FIRST_TIER_OPS)
    body = template("python.py.tmpl").replace("{{GENERATED_OPERATIONS}}", generated)
    return BANNER_PY + "\n" + body


# --------------------------------------------------------------------------- ts
def ts_type(t):
    return {"string": "string", "int": "number", "number": "number", "bool": "boolean",
            "string[]": "string[]", "object": "Record<string, any>"}[t]


def emit_ts(op):
    pp, qp, bp, req, opt = parts(op)
    sig = [("%s: %s" % (camel(x["name"]), ts_type(x["type"]))) for x in req]
    if opt:
        fields = "; ".join("%s?: %s" % (camel(x["name"]), ts_type(x["type"])) for x in opt)
        sig.append("opts: RequestControlOpts & { %s } = {}" % fields)
    else:
        sig.append("opts: RequestControlOpts = {}")

    fmt = op["path"]
    for x in pp:
        fmt = fmt.replace("{%s}" % x["name"], "${enc(String(%s))}" % camel(x["name"]))

    lines = []
    path_expr = "`%s`" % fmt
    if qp:
        lines.append("    const query = new URLSearchParams();")
        for x in qp:
            local = "opts.%s" % camel(x["name"]) if x.get("optional") else camel(x["name"])
            if x["type"] == "object":
                lines.append('    validateMetadata(%s, "%s query");' % (local, x["name"]))
                lines.append("    for (const [key, value] of Object.entries(%s ?? {}).sort(([a], [b]) => a.localeCompare(b))) {" % local)
                lines.append('      if (key.trim()) query.set("%s." + key, value as string);' % x["name"])
                lines.append("    }")
            elif x.get("optional"):
                lines.append('    if (%s !== undefined) query.set("%s", String(%s));' % (local, x["name"], local))
            else:
                lines.append('    query.set("%s", String(%s));' % (x["name"], local))
        lines.append('    const path = %s + (query.size ? `?${query.toString()}` : "");' % path_expr)
        path_expr = "path"

    call = 'this.request("%s", %s' % (op["method"], path_expr)
    if bp:
        items = []
        for x in bp:
            src = camel(x["name"]) if not x.get("optional") else "opts.%s" % camel(x["name"])
            items.append("%s: %s" % (x["name"], src))
        call += ", { %s }" % ", ".join(items)
    else:
        call += ", undefined"
    call += ", opts)"
    lines.append("    return %s;" % call)
    return ("  async %s(%s): Promise<any> {\n%s\n  }\n"
            % (camel(op["name"]), ", ".join(sig), "\n".join(lines)))


def gen_ts():
    generated = "\n".join(emit_ts(op) for op in GENERATED_FIRST_TIER_OPS)
    body = template("typescript.ts.tmpl").replace("{{GENERATED_OPERATIONS}}", generated)
    return BANNER_C + "\n" + body


# --------------------------------------------------------------------------- go
def go_type(t):
    return {"string": "string", "int": "int64", "number": "float64", "bool": "bool",
            "string[]": "[]string", "object": "map[string]any"}[t]


def emit_go(op):
    pp, qp, bp, req, opt = parts(op)
    sig = [("%s %s" % (camel(x["name"]), go_type(x["type"]))) for x in req]
    if opt:
        sig.append("opts map[string]any")
    lines = []

    fmt = op["path"]
    enc_args = []
    for x in pp:
        fmt = fmt.replace("{%s}" % x["name"], "%s")
        enc_args.append("enc(%s)" % camel(x["name"]))
    if enc_args:
        lines.append('\tpath := fmt.Sprintf("%s", %s)' % (fmt, ", ".join(enc_args)))
        pathvar = "path"
    else:
        pathvar = '"%s"' % fmt

    if qp:
        if pathvar != "path":
            lines.append("\tpath := %s" % pathvar)
            pathvar = "path"
        lines.append("\tquery := url.Values{}")
        for x in qp:
            local = 'opts["%s"]' % x["name"] if x.get("optional") else camel(x["name"])
            if x["type"] == "object":
                lines.append("\tif raw, ok := %s; ok && raw != nil {" % local)
                lines.append("\t\tswitch values := raw.(type) {")
                lines.append("\t\tcase map[string]string:")
                lines.append("\t\t\tfor key, value := range values {")
                lines.append("\t\t\t\tquery.Set(\"%s.\"+key, value)" % x["name"])
                lines.append("\t\t\t}")
                lines.append("\t\tcase map[string]any:")
                lines.append("\t\t\tfor key, value := range values {")
                lines.append("\t\t\t\tquery.Set(\"%s.\"+key, fmt.Sprint(value))" % x["name"])
                lines.append("\t\t\t}")
                lines.append("\t\tdefault:")
                lines.append("\t\t\treturn nil, fmt.Errorf(\"fiducia: %s query must be a map\")" % x["name"])
                lines.append("\t\t}")
                lines.append("\t}")
            elif x.get("optional"):
                lines.append("\tif value, ok := %s; ok && value != nil {" % local)
                lines.append("\t\tquery.Set(\"%s\", fmt.Sprint(value))" % x["name"])
                lines.append("\t}")
            else:
                lines.append("\tquery.Set(\"%s\", fmt.Sprint(%s))" % (x["name"], local))
        lines.append("\tif encoded := query.Encode(); encoded != \"\" {")
        lines.append("\t\tpath += \"?\" + encoded")
        lines.append("\t}")

    req_body = [x for x in bp if not x.get("optional")]
    if bp:
        inits = ", ".join('"%s": %s' % (x["name"], camel(x["name"])) for x in req_body)
        lines.append("\tbody := map[string]any{%s}" % inits)
        for x in bp:
            if x.get("optional"):
                lines.append('\tif value, ok := opts["%s"]; ok {' % x["name"])
                lines.append('\t\tbody["%s"] = value' % x["name"])
                lines.append("\t}")
        bodyvar = "body"
    else:
        bodyvar = "nil"
    lines.append('\treturn c.request("%s", %s, %s)' % (op["method"], pathvar, bodyvar))
    return ("// %s %s\nfunc (c *Client) %s(%s) (map[string]any, error) {\n%s\n}\n"
            % (pascal(op["name"]), op.get("doc", ""), pascal(op["name"]),
               ", ".join(sig), "\n".join(lines)))


def gen_go():
    generated = "\n".join(emit_go(op) for op in GENERATED_FIRST_TIER_OPS)
    body = template("go.go.tmpl").replace("{{GENERATED_OPERATIONS}}", generated)
    return (BANNER_C + "\n" + body).rstrip() + "\n"


# ------------------------------------------------------------------- rust-wasm
# A Rust client compiled to WebAssembly. Unlike clients/rust (blocking `ureq`),
# the wasm build cannot open sockets, so its transport is the browser `fetch`
# API via wasm-bindgen. Every op is an async method; wasm-bindgen exports the
# snake_case names to JS as camelCase. Kept separate from clients/rust so that
# native client stays a plain blocking crate.
RUST_WASM_PRE = BANNER_C + '''
//! Fiducia client (Rust -> WebAssembly) — generated. Transport is the global
//! `fetch` (browser main thread, Web Workers, and Node 18+/Deno).
//!
//! Build:  wasm-pack build clients/rust-wasm --target web
//!
//! Every operation is an `async` method (exported to JS as camelCase) that
//! resolves to the parsed JSON response, or rejects with `{ status, body }` on a
//! non-2xx response or transport failure. Pass an optional `timeout_ms` to the
//! constructor (or `setTimeoutMs`) to bound each request, and `setHeader` to
//! attach default headers such as `Authorization` to every request.
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use wasm_bindgen_futures::JsFuture;
use web_sys::{AbortSignal, Request, RequestInit, RequestRedirect, Response, ResponseType};

// web-sys (0.3) doesn't bind the `AbortSignal.timeout` static, so bind the
// runtime one directly (available in browsers 2022+, Node 17.3+, and Deno).
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = AbortSignal, js_name = timeout)]
    fn abort_signal_timeout(ms: f64) -> AbortSignal;
}

/// URL-encode a path/query segment via the JS `encodeURIComponent`.
fn enc(s: &str) -> String {
    String::from(js_sys::encode_uri_component(s))
}

/// Build the `{ status, body }` rejection value used for every failure.
fn err(status: u16, body: JsValue) -> JsValue {
    let o = js_sys::Object::new();
    let _ = js_sys::Reflect::set(&o, &JsValue::from_str("status"), &JsValue::from(status));
    let _ = js_sys::Reflect::set(&o, &JsValue::from_str("body"), &body);
    o.into()
}

// Integer fields cross JS as f64. Reject values a JSON integer can't faithfully
// represent (NaN/Infinity, fractional, or beyond 2^53) so the client fails loudly
// instead of silently coercing (`NaN as i64` == 0, `Infinity as i64` == i64::MAX).
const MAX_SAFE_INT: f64 = 9_007_199_254_740_991.0;
fn checked_int(v: f64, field: &str) -> Result<i64, JsValue> {
    if !v.is_finite() || v.fract() != 0.0 || v.abs() > MAX_SAFE_INT {
        return Err(err(0, JsValue::from_str(&format!(
            "field `{field}` must be a safe integer, got {v}"
        ))));
    }
    Ok(v as i64)
}

#[wasm_bindgen]
pub struct FiduciaClient {
    base: String,
    timeout_ms: Option<f64>,
    // Default headers applied to every request (e.g. Authorization). Header
    // names are case-insensitive; the last value set for a name wins.
    headers: Vec<(String, String)>,
}

#[wasm_bindgen]
impl FiduciaClient {
    /// `timeout_ms` is optional (pass `undefined` for none); when set, each
    /// request aborts after that many milliseconds via `AbortSignal.timeout`.
    #[wasm_bindgen(constructor)]
    pub fn new(base_url: &str, timeout_ms: Option<f64>) -> FiduciaClient {
        FiduciaClient { base: base_url.trim_end_matches('/').to_string(), timeout_ms, headers: Vec::new() }
    }

    /// Set (or clear, with `undefined`) the per-request timeout in milliseconds.
    #[wasm_bindgen(js_name = setTimeoutMs)]
    pub fn set_timeout_ms(&mut self, timeout_ms: Option<f64>) {
        self.timeout_ms = timeout_ms;
    }

    /// Set a default header sent on every request — e.g. `Authorization`,
    /// `Idempotency-Key`. Setting the same name again replaces it.
    #[wasm_bindgen(js_name = setHeader)]
    pub fn set_header(&mut self, name: &str, value: &str) {
        self.headers.retain(|(n, _)| !n.eq_ignore_ascii_case(name));
        self.headers.push((name.to_string(), value.to_string()));
    }

    /// Remove a previously set default header (no-op if absent).
    #[wasm_bindgen(js_name = removeHeader)]
    pub fn remove_header(&mut self, name: &str) {
        self.headers.retain(|(n, _)| !n.eq_ignore_ascii_case(name));
    }

    async fn request(&self, method: &str, path: String, body: Option<String>) -> Result<JsValue, JsValue> {
        let opts = RequestInit::new();
        opts.set_method(method);
        // Hard-reject redirects: never auto-follow a 3xx, which would replay this
        // (possibly mutating) request and its auth/idempotency headers to an
        // attacker-controlled Location, including an https->http downgrade.
        opts.set_redirect(RequestRedirect::Manual);
        if let Some(ref b) = body {
            opts.set_body(&JsValue::from_str(b));
        }
        // Bound the request with AbortSignal.timeout (browser/worker/Node18+/Deno).
        if let Some(ms) = self.timeout_ms {
            opts.set_signal(Some(&abort_signal_timeout(ms)));
        }
        let url = format!("{}{}", self.base, path);
        let request = Request::new_with_str_and_init(&url, &opts).map_err(|e| err(0, e))?;
        let req_headers = request.headers();
        if body.is_some() {
            req_headers.set("content-type", "application/json").map_err(|e| err(0, e))?;
        }
        // Default headers (auth, idempotency key, ...) override content-type only
        // if the caller explicitly set that name.
        for (name, value) in &self.headers {
            req_headers.set(name, value).map_err(|e| err(0, e))?;
        }
        // Resolve `fetch` from the global scope so the client works on the
        // browser main thread, in Web Workers, and in Node 18+/Deno (global
        // fetch) — not just `window`.
        let global = js_sys::global();
        let fetch = js_sys::Reflect::get(&global, &JsValue::from_str("fetch"))
            .ok()
            .and_then(|f| f.dyn_into::<js_sys::Function>().ok())
            .ok_or_else(|| err(0, JsValue::from_str("no global fetch available")))?;
        let promise: js_sys::Promise = fetch
            .call1(&global, &request)
            .map_err(|e| err(0, e))?
            .dyn_into()
            .map_err(|e| err(0, e))?;
        let resp_value = JsFuture::from(promise).await.map_err(|e| err(0, e))?;
        let resp: Response = resp_value.dyn_into().map_err(|e| err(0, e))?;
        // With redirect:"manual", a redirected fetch yields an opaque-redirect
        // response (status 0) in browsers/workers, or a readable 3xx in Node/Deno.
        // Reject either rather than following it.
        if resp.type_() == ResponseType::Opaqueredirect || (resp.status() >= 300 && resp.status() < 400) {
            return Err(err(resp.status(), JsValue::from_str("fiducia: refusing to follow redirect")));
        }
        let text_value = JsFuture::from(resp.text().map_err(|e| err(0, e))?).await.map_err(|e| err(0, e))?;
        let text = text_value.as_string().unwrap_or_default();
        // Parse JSON; if the body isn't JSON, surface the raw text (not null) so
        // non-JSON error pages (proxies, 502s) remain diagnosable.
        let parsed = if text.is_empty() {
            JsValue::NULL
        } else {
            js_sys::JSON::parse(&text).unwrap_or_else(|_| JsValue::from_str(&text))
        };
        if !resp.ok() {
            return Err(err(resp.status(), parsed));
        }
        Ok(parsed)
    }
'''

# `int` maps to f64 (JS `number`), not i64: wasm-bindgen would expose i64 as a JS
# `bigint`, which mismatches the response JSON (numbers) and the sibling TS
# client. Integer-valued params are re-cast to i64 when building the JSON body so
# the wire form stays a clean integer (e.g. 30000, never 30000.0).
RUST_WASM_TYPE = {"string": "String", "int": "f64", "number": "f64", "bool": "bool",
                  "string[]": "Vec<String>", "object": "JsValue"}


def _rw_scalar_enc(typ, var):
    # A scalar path/query value, encoded for a URL.
    if typ == "string":
        return "enc(&%s)" % var
    if typ == "int":
        return "enc(&(%s as i64).to_string())" % var
    return "enc(&%s.to_string())" % var


def _rw_json_scalar(typ, var, field):
    # A scalar body value as a serde_json::Value. Integers go through checked_int
    # (fail loudly on NaN/Infinity/fractional/unsafe) and land as a clean integer.
    if typ == "int":
        return 'serde_json::json!(checked_int(%s, "%s")?)' % (var, field)
    return "serde_json::json!(%s)" % var


def _rw_object_query_lines(name):
    # An object query param expands to `name.KEY=VALUE` pairs, ANDed by the
    # server (PROTOCOL.md: e.g. metadata.region=us-east). Not a JSON blob.
    # dyn_ref returns None for null/undefined/non-objects, so the loop is skipped.
    return [
        "        if let Some(_obj) = %s.dyn_ref::<js_sys::Object>() {" % name,
        "            for _entry in js_sys::Object::entries(_obj).iter() {",
        "                let _pair = js_sys::Array::from(&_entry);",
        "                let _k = _pair.get(0).as_string().unwrap_or_default();",
        "                if _k.is_empty() { continue; }",
        "                let _v = _pair.get(1);",
        # Contract is Record<string,string>; reject non-string values loudly
        # instead of silently JSON-stringifying them (cross-client surprises).
        "                let _vs = match _v.as_string() {",
        "                    Some(_s) => _s,",
        '                    None => return Err(err(0, JsValue::from_str(&format!("%s.{_k} must be a string")))),' % name,
        "                };",
        '                _q.push(format!("%s.{}={}", enc(&_k), enc(&_vs)));' % name,
        "            }",
        "        }",
    ]


def _rw_query_lines(x):
    # Code that appends one query param to `_q` (optional ones only when present).
    name = x["name"]
    if x["type"] == "object":
        return _rw_object_query_lines(name)
    if not x.get("optional"):
        return ['        _q.push(format!("%s={}", %s));' % (name, _rw_scalar_enc(x["type"], name))]
    return ["        if let Some(v) = %s {" % name,
            '            _q.push(format!("%s={}", %s));' % (name, _rw_scalar_enc(x["type"], "v")),
            "        }"]


def _rw_body_value(x):
    # A required body param -> serde_json::Value expression.
    if x["type"] == "object":
        return "serde_wasm_bindgen::from_value(%s).map_err(|e| err(0, e.into()))?" % x["name"]
    if x["type"] == "string":
        return "serde_json::Value::String(%s)" % x["name"]
    return _rw_json_scalar(x["type"], x["name"], x["name"])


def emit_rust_wasm(op):
    pp, qp, bp, req, opt = parts(op)
    sig = ["&self"]
    for x in req:
        sig.append("%s: %s" % (x["name"], RUST_WASM_TYPE[x["type"]]))
    for x in opt:
        # Optional objects stay a nullable JsValue; other optionals are Option<T>.
        if x["type"] == "object":
            sig.append("%s: JsValue" % x["name"])
        else:
            sig.append("%s: Option<%s>" % (x["name"], RUST_WASM_TYPE[x["type"]]))
    lines = []
    # path (path params only; query is appended below so optionals can be omitted)
    fmt = op["path"]
    penc = []
    for x in pp:
        fmt = fmt.replace("{%s}" % x["name"], "{}")
        penc.append(_rw_scalar_enc(x["type"], x["name"]))
    decl = "let mut path" if qp else "let path"
    if penc:
        lines.append('        %s = format!("%s", %s);' % (decl, fmt, ", ".join(penc)))
    else:
        lines.append('        %s = String::from("%s");' % (decl, fmt))
    # query string (required always, optional only when provided)
    if qp:
        lines.append("        let mut _q: Vec<String> = Vec::new();")
        for x in qp:
            lines.extend(_rw_query_lines(x))
        lines.append("        if !_q.is_empty() {")
        lines.append("            path.push('?');")
        lines.append('            path.push_str(&_q.join("&"));')
        lines.append("        }")
    # body map
    if bp:
        lines.append("        let mut _body = serde_json::Map::new();")
        for x in bp:
            if not x.get("optional"):
                lines.append('        _body.insert("%s".to_string(), %s);' % (x["name"], _rw_body_value(x)))
            elif x["type"] == "object":
                lines.append("        if !%s.is_null() && !%s.is_undefined() {" % (x["name"], x["name"]))
                lines.append('            _body.insert("%s".to_string(), serde_wasm_bindgen::from_value(%s).map_err(|e| err(0, e.into()))?);'
                             % (x["name"], x["name"]))
                lines.append("        }")
            else:
                lines.append("        if let Some(v) = %s {" % x["name"])
                lines.append('            _body.insert("%s".to_string(), %s);' % (x["name"], _rw_json_scalar(x["type"], "v", x["name"])))
                lines.append("        }")
        lines.append("        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();")
        bodyarg = "Some(_payload)"
    else:
        bodyarg = "None"
    lines.append('        self.request("%s", path, %s).await' % (op["method"], bodyarg))
    doc = op.get("doc", "")
    # Export camelCase JS names to match the TypeScript client's surface.
    return ('    /// %s\n    #[wasm_bindgen(js_name = %s)]\n    pub async fn %s(%s) -> Result<JsValue, JsValue> {\n%s\n    }\n'
            % (doc, camel(op["name"]), op["name"], ", ".join(sig), "\n".join(lines)))


def gen_rust_wasm():
    return RUST_WASM_PRE + "\n" + "\n".join(emit_rust_wasm(op) for op in OPS) + "}\n"


# ------------------------------------------------------------------------- docs
def gen_markdown():
    rows = ["<!-- GENERATED by generate.py from operations.json — DO NOT EDIT BY HAND. -->",
            "# Fiducia HTTP endpoint reference",
            "",
            "Every client in `clients/` is generated from `operations.json`; this table is",
            "too. `?param` marks an optional argument.",
            "",
            "| Method | Path | Args | Description |",
            "|--------|------|------|-------------|"]
    for op in OPS:
        args = ", ".join("`%s`%s" % (p["name"], "?" if p.get("optional") else "") for p in op["params"])
        rows.append("| `%s` | `%s` | %s | %s |" % (op["method"], op["path"], args or "—", op.get("doc", "")))
    return "\n".join(rows) + "\n"


TARGETS = {
    "python": ("clients/python/fiducia.py", gen_python),
    "ts": ("clients/ts/fiducia.ts", gen_ts),
    "go": ("clients/go/fiducia.go", gen_go),
    "rust-wasm": ("clients/rust-wasm/src/lib.rs", gen_rust_wasm),
    "docs": ("ENDPOINTS.md", gen_markdown),
}


def main():
    args = sys.argv[1:]
    # --check <targets...> verifies targets without writing (exit 1 on drift).
    # With no explicit target it checks every committed generated artifact.
    check = "--check" in args
    want = [a for a in args if not a.startswith("--")] or list(TARGETS)
    drift = 0
    for lang in want:
        rel, gen = TARGETS[lang]
        path = os.path.join(ROOT, rel)
        content = gen()
        if check:
            current = open(path).read() if os.path.exists(path) else None
            if current != content:
                print("drift: %s (run: python3 generate.py %s)" % (rel, lang))
                drift += 1
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        open(path, "w").write(content)
        print("generated %-8s -> %s (%d ops)" % (lang, rel, len(OPS)))
    if check:
        if drift:
            sys.exit(1)
        print("up to date (%d target(s))." % len(want))


if __name__ == "__main__":
    main()
