#!/usr/bin/env python3
"""Generate the complete Dart publication unit from operations.json.

The reviewed `clients/dart/fiducia.dart` file owns transport, retries, sync,
secret helpers, and established ergonomic methods. This generator inserts only
manifest operations that are not already declared by that reviewed class. The
result is a standalone Dart library suitable for pub.dev and for the repository
surface-contract gate.

Generated output is evidence derived from `operations.json`; it never changes
that authored HTTP-operation authority.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent
OPERATIONS = ROOT / "operations.json"
REVIEWED_SOURCE = ROOT / "clients" / "dart" / "fiducia.dart"
DEFAULT_OUTPUT = ROOT / "clients" / "dart" / "generated" / "fiducia_client.dart"
BANNER = (
    "// GENERATED by generate_dart.py from operations.json + "
    "clients/dart/fiducia.dart.\n"
    "// DO NOT EDIT: change the reviewed source or operation manifest and "
    "regenerate.\n"
)

DART_RESERVED = {
    "abstract", "as", "assert", "async", "await", "base", "break", "case",
    "catch", "class", "const", "continue", "covariant", "default",
    "deferred", "do", "dynamic", "else", "enum", "export", "extends",
    "extension", "external", "factory", "false", "final", "finally", "for",
    "from", "get", "hide", "if", "implements", "import", "in", "interface",
    "is", "late", "library", "mixin", "new", "null", "of", "on",
    "operator", "part", "required", "rethrow", "return", "sealed", "set",
    "show", "static", "super", "switch", "sync", "this", "throw", "true",
    "try", "typedef", "var", "void", "when", "while", "with", "yield",
}

TYPE_MAP = {
    "string": "String",
    "int": "int",
    "number": "num",
    "bool": "bool",
    "string[]": "List<String>",
    "int[]": "List<int>",
    "object[]": "List<Map<String, Object?>>",
    "object": "Map<String, Object?>",
    "any": "Object?",
}


def pascal(value: str) -> str:
    return "".join(
        part[:1].upper() + part[1:] for part in value.split("_") if part
    )


def camel(value: str) -> str:
    rendered = pascal(value)
    return rendered[:1].lower() + rendered[1:]


def dart_ident(wire_name: str) -> str:
    value = camel(wire_name)
    return value + "_" if value in DART_RESERVED else value


def dart_type(wire_type: str, *, optional: bool = False) -> str:
    try:
        value = TYPE_MAP[wire_type]
    except KeyError as exc:
        raise ValueError(f"unsupported Dart wire type: {wire_type!r}") from exc
    if optional and not value.endswith("?"):
        return value + "?"
    return value


def declared_methods(source: str) -> set[str]:
    pattern = re.compile(
        r"(?m)^  (?:[A-Za-z_][A-Za-z0-9_<>,.? ]*\s+)"
        r"([A-Za-z_][A-Za-z0-9_]*)\s*\("
    )
    return {match.group(1) for match in pattern.finditer(source)}


def parts(operation: dict[str, Any]) -> tuple[list[dict[str, Any]], ...]:
    params = operation.get("params", [])
    path = [item for item in params if item["in"] == "path"]
    query = [item for item in params if item["in"] == "query"]
    body = [item for item in params if item["in"] == "body"]
    required = [item for item in params if not item.get("optional")]
    optional = [item for item in params if item.get("optional")]
    return path, query, body, required, optional


def dart_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def render_path(
    operation: dict[str, Any], path_params: list[dict[str, Any]]
) -> str:
    value = operation["path"]
    for param in path_params:
        local = dart_ident(param["name"])
        value = value.replace(
            "{%s}" % param["name"],
            "${_enc(%s.toString())}" % local,
        )
    return "'%s'" % dart_string(value)


def emit_method(operation: dict[str, Any]) -> str:
    path_params, query_params, body_params, required, optional = parts(operation)
    required_args = [
        "%s %s" % (dart_type(item["type"]), dart_ident(item["name"]))
        for item in required
    ]
    named_args = [
        "%s %s"
        % (
            dart_type(item["type"], optional=True),
            dart_ident(item["name"]),
        )
        for item in optional
    ]
    named_args.append("FiduciaRequestOptions? requestOptions")

    signature_lines = ["  Future<dynamic> %s(" % camel(operation["name"])]
    signature_lines.extend("    %s," % item for item in required_args)
    signature_lines.append("    {")
    signature_lines.extend("    %s," % item for item in named_args)
    signature_lines.append("  }) async {")

    lines: list[str] = []
    path_expr = render_path(operation, path_params)
    if query_params:
        lines.append("    final path = _generatedQueryPath(")
        lines.append("      %s," % path_expr)
        lines.append("      <String, Object?>{")
        for item in query_params:
            lines.append(
                "        '%s': %s,"
                % (item["name"], dart_ident(item["name"]))
            )
        lines.extend(["      },", "    );"])
        path_expr = "path"

    if body_params:
        lines.append("    final body = <String, Object?>{")
        for item in body_params:
            if not item.get("optional"):
                lines.append(
                    "      '%s': %s,"
                    % (item["name"], dart_ident(item["name"]))
                )
        lines.append("    };")
        for item in body_params:
            if item.get("optional"):
                local = dart_ident(item["name"])
                lines.extend(
                    [
                        "    if (%s != null) {" % local,
                        "      body['%s'] = %s;" % (item["name"], local),
                        "    }",
                    ]
                )
        body_expr = "body"
    else:
        body_expr = "null"

    lock_acquire = operation["name"] in {
        "lock_acquire",
        "lock_acquire_many",
        "semaphore_acquire",
    }
    call = "    return _request('%s', %s, %s, requestOptions" % (
        operation["method"],
        path_expr,
        body_expr,
    )
    if lock_acquire:
        call += ", true"
    call += ");"
    lines.extend([call, "  }"])

    doc = operation.get("doc", "").replace("\n", " ").strip()
    docs = ["  /// %s" % doc] if doc else []
    return "\n".join(docs + signature_lines + lines)


QUERY_HELPER = r"""
  String _generatedQueryPath(
    String path,
    Map<String, Object?> values,
  ) {
    final pairs = <String>[];
    final names = values.keys.toList()..sort();
    for (final name in names) {
      final value = values[name];
      if (value == null) continue;
      if (value is Map) {
        final entries = value.entries.toList()
          ..sort((left, right) =>
              left.key.toString().compareTo(right.key.toString()));
        for (final entry in entries) {
          final nested = entry.value;
          if (nested == null) continue;
          final key = entry.key.toString();
          pairs.add(
            '${Uri.encodeQueryComponent('$name.$key')}='
            '${Uri.encodeQueryComponent(nested.toString())}',
          );
        }
      } else {
        pairs.add(
          '${Uri.encodeQueryComponent(name)}='
          '${Uri.encodeQueryComponent(value.toString())}',
        );
      }
    }
    return pairs.isEmpty ? path : '$path?${pairs.join('&')}';
  }
""".strip("\n")


def generate(source: str, operations: list[dict[str, Any]]) -> str:
    current = declared_methods(source)
    missing = [
        item for item in operations if camel(item["name"]) not in current
    ]
    if not source.rstrip().endswith("}"):
        raise ValueError(
            "reviewed Dart source must end with the FiduciaClient closing brace"
        )
    base = source.rstrip()[:-1].rstrip()
    generated = [
        "",
        "  // --- generated manifest operations ---",
        "  // Derived from operations.json; reviewed methods above take precedence.",
        QUERY_HELPER,
    ]
    generated.extend("\n" + emit_method(item) for item in missing)
    generated.extend(["}", ""])
    return BANNER + base + "\n" + "\n".join(generated)


def load_operations() -> list[dict[str, Any]]:
    document = json.loads(OPERATIONS.read_text(encoding="utf-8"))
    operations = document.get("operations")
    if not isinstance(operations, list) or not operations:
        raise ValueError(
            "operations.json must contain a nonempty operations array"
        )
    return operations


def assert_complete(
    rendered: str, operations: list[dict[str, Any]]
) -> None:
    methods = declared_methods(rendered)
    missing = sorted(
        camel(item["name"])
        for item in operations
        if camel(item["name"]) not in methods
    )
    if missing:
        raise ValueError(
            "generated Dart client is missing: %s" % ", ".join(missing)
        )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail when committed output differs"
    )
    parser.add_argument(
        "--stdout", action="store_true", help="write generated source to stdout"
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    source = REVIEWED_SOURCE.read_text(encoding="utf-8")
    operations = load_operations()
    rendered = generate(source, operations)
    assert_complete(rendered, operations)

    output = args.output if args.output.is_absolute() else ROOT / args.output
    if args.stdout:
        print(rendered, end="")
        return 0
    if args.check:
        current = (
            output.read_text(encoding="utf-8") if output.is_file() else ""
        )
        if current != rendered:
            print("dart generation drift: %s" % output.relative_to(ROOT))
            for line in difflib.unified_diff(
                current.splitlines(),
                rendered.splitlines(),
                fromfile=str(output),
                tofile="generated",
                n=2,
            ):
                print(line)
            return 1
        print("dart generation up to date: %s" % output.relative_to(ROOT))
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    print(
        "generated Dart publication unit: %s (%d manifest operations)"
        % (output.relative_to(ROOT), len(operations))
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
