# GENERATED by generate.py from operations.json — DO NOT EDIT BY HAND.
"""Fiducia client (Python) — generated. Zero deps (stdlib urllib).

    c = FiduciaClient("https://api.fiducia.cloud")
    g = c.lock_acquire_many(["a", "b"], holder="w1", ttl_ms=30000)
    c.lock_release("w1", g["result"]["output"]["fencing_token"])
"""
import json as _json
import urllib.error
import urllib.parse
import urllib.request


class FiduciaError(Exception):
    def __init__(self, status, body):
        super().__init__("fiducia: HTTP %s" % status)
        self.status, self.body = status, body


def _enc(s):
    return urllib.parse.quote(str(s), safe="")


class FiduciaClient:
    def __init__(self, base_url, timeout=30):
        self.base, self.timeout = base_url.rstrip("/"), timeout

    def _request(self, method, path, body=None):
        data = _json.dumps(body).encode() if body is not None else None
        req = urllib.request.Request(self.base + path, data=data, method=method)
        if data is not None:
            req.add_header("content-type", "application/json")
        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as r:
                text = r.read().decode()
                return _json.loads(text) if text else None
        except urllib.error.HTTPError as e:
            text = e.read().decode()
            raise FiduciaError(e.code, _json.loads(text) if text else None)

    def health(self):
        """Liveness probe."""
        return self._request("GET", "/healthz")

    def status(self):
        """Per-shard consensus status."""
        return self._request("GET", "/v1/status")

    def lock_get(self, key):
        """Inspect a lock member key: holder, the held union, and the FIFO wait queue."""
        return self._request("GET", "/v1/locks?key=%s" % _enc(key))

    def lock_acquire(self, key, holder=None, ttl_ms=None, wait=None):
        """Acquire a single-key lock (try-lock unless wait)."""
        return self._request("POST", "/v1/locks/acquire", {"key": key, "holder": holder, "ttl_ms": ttl_ms, "wait": wait})

    def lock_acquire_many(self, keys, holder=None, ttl_ms=None, wait=None):
        """Multi-key UNION lock: all-or-nothing across the set; conflicts on any member key."""
        return self._request("POST", "/v1/locks/acquire", {"keys": keys, "holder": holder, "ttl_ms": ttl_ms, "wait": wait})

    def lock_release(self, holder, fencing_token):
        """Release the whole grant (every member key) by its fencing token."""
        return self._request("POST", "/v1/locks/release", {"holder": holder, "fencing_token": fencing_token})

    def semaphore_get(self, key):
        """Inspect a semaphore: limit, holders, free permits, queue."""
        return self._request("GET", "/v1/semaphores?key=%s" % _enc(key))

    def semaphore_acquire(self, key, limit, holder=None, ttl_ms=None, wait=None):
        """Take a permit of a counting semaphore (up to limit holders)."""
        return self._request("POST", "/v1/semaphores/acquire", {"key": key, "limit": limit, "holder": holder, "ttl_ms": ttl_ms, "wait": wait})

    def semaphore_release(self, key, holder, fencing_token):
        """Return one permit (admits the next FIFO waiter)."""
        return self._request("POST", "/v1/semaphores/release", {"key": key, "holder": holder, "fencing_token": fencing_token})

    def idempotency_get(self, key):
        """Inspect an active idempotency record."""
        return self._request("GET", "/v1/idempotency?key=%s" % _enc(key))

    def idempotency_claim(self, key, owner=None, ttl_ms=None, ttl=None, metadata=None):
        """Claim an idempotency key; first claimant wins until TTL expiry, duplicates return the existing record."""
        return self._request("POST", "/v1/idempotency/claim", {"key": key, "owner": owner, "ttl_ms": ttl_ms, "ttl": ttl, "metadata": metadata})

    def idempotency_complete(self, key, owner, fencing_token, result=None):
        """Mark a claimed idempotency key complete and optionally store a replayable result."""
        return self._request("POST", "/v1/idempotency/complete", {"key": key, "owner": owner, "fencing_token": fencing_token, "result": result})

    def kv_get(self, key):
        """Read a config key."""
        return self._request("GET", "/v1/kv?key=%s" % _enc(key))

    def kv_put(self, key, value, ttl_ms=None, prev_revision=None):
        """Write a config key; prev_revision is a compare-and-swap guard (0 = must-not-exist)."""
        return self._request("PUT", "/v1/kv?key=%s" % _enc(key), {"value": value, "ttl_ms": ttl_ms, "prev_revision": prev_revision})

    def kv_delete(self, key):
        """Delete a config key."""
        return self._request("DELETE", "/v1/kv?key=%s" % _enc(key))

    def counter_get(self, key):
        """Read a counter's value and revision; absent reads as found=false (treat as 0)."""
        return self._request("GET", "/v1/counters?key=%s" % _enc(key))

    def counter_add(self, key, delta, prev_revision=None):
        """Atomically add delta (may be negative); prev_revision makes it a compare-and-set."""
        return self._request("POST", "/v1/counters/add", {"key": key, "delta": delta, "prev_revision": prev_revision})

    def counter_set(self, key, value, prev_revision=None):
        """Set a counter to an absolute value (e.g. reset to 0); prev_revision makes it a compare-and-set."""
        return self._request("POST", "/v1/counters/set", {"key": key, "value": value, "prev_revision": prev_revision})

    def election_get(self, name):
        """Observe the current holder of a named election."""
        return self._request("GET", "/v1/elections/%s" % _enc(name))

    def election_campaign(self, name, candidate, ttl_ms, metadata=None):
        """Campaign for leadership with optional candidate metadata; wins if currently unheld. Returns a fencing token on win."""
        return self._request("POST", "/v1/elections/%s/campaign" % _enc(name), {"candidate": candidate, "ttl_ms": ttl_ms, "metadata": metadata})

    def election_renew(self, name, candidate, fencing_token):
        """Extend the lease; requires the held fencing token."""
        return self._request("POST", "/v1/elections/%s/renew" % _enc(name), {"candidate": candidate, "fencing_token": fencing_token})

    def election_resign(self, name, candidate, fencing_token):
        """Step down; requires the held fencing token."""
        return self._request("POST", "/v1/elections/%s/resign" % _enc(name), {"candidate": candidate, "fencing_token": fencing_token})

    def service_instances(self, service, metadata=None):
        """List live instances of a service, optionally filtered by exact metadata matches."""
        return self._request("GET", "/v1/services/%s?metadata=%s" % (_enc(service), _enc(metadata)))

    def service_register(self, service, instance_id, address, ttl_ms, metadata=None):
        """Register/refresh an instance with a TTL lease and optional metadata."""
        return self._request("PUT", "/v1/services/%s/instances/%s" % (_enc(service), _enc(instance_id)), {"address": address, "ttl_ms": ttl_ms, "metadata": metadata})

    def service_heartbeat(self, service, instance_id, ttl_ms=None):
        """Renew an instance lease before it expires."""
        return self._request("POST", "/v1/services/%s/instances/%s/heartbeat" % (_enc(service), _enc(instance_id)), {"ttl_ms": ttl_ms})

    def service_deregister(self, service, instance_id):
        """Remove an instance from the registry."""
        return self._request("DELETE", "/v1/services/%s/instances/%s" % (_enc(service), _enc(instance_id)))

    def rate_limit_get(self, tenant, key):
        """Current limiter state for a tenant/key."""
        return self._request("GET", "/v1/rate-limit/%s/%s" % (_enc(tenant), _enc(key)))

    def rate_limit_check(self, tenant, key, algorithm, limit, window_ms, refill_per_second=None, cost=None):
        """Atomic check-and-decrement (token_bucket | sliding_window). Returns {allowed, remaining}."""
        return self._request("POST", "/v1/rate-limit/%s/%s/check" % (_enc(tenant), _enc(key)), {"algorithm": algorithm, "limit": limit, "window_ms": window_ms, "refill_per_second": refill_per_second, "cost": cost})

    def schedule_get(self, name):
        """Read a schedule definition."""
        return self._request("GET", "/v1/cron/schedules/%s" % _enc(name))

    def schedule_upsert(self, name, target, cron=None, one_shot_at_ms=None, delivery=None, max_retries=None):
        """Create/update a schedule. target = {kind: webhook|queue|grpc, ...}. Exactly one of cron / one_shot_at_ms."""
        return self._request("PUT", "/v1/cron/schedules/%s" % _enc(name), {"target": target, "cron": cron, "one_shot_at_ms": one_shot_at_ms, "delivery": delivery, "max_retries": max_retries})

    def schedule_record_run(self, name, fire_id, fired_at_ms=None):
        """Record a fire; duplicate fire_id is deduped (exactly-once)."""
        return self._request("POST", "/v1/cron/schedules/%s/runs" % _enc(name), {"fire_id": fire_id, "fired_at_ms": fired_at_ms})

    def schedule_history(self, name):
        """Recent run history."""
        return self._request("GET", "/v1/cron/schedules/%s/history" % _enc(name))
