// GENERATED by generate.py from operations.json — DO NOT EDIT BY HAND.
// Package fiducia is a generated, zero-dependency HTTP client (stdlib net/http).
package fiducia

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
)

type Error struct {
	Status int
	Body   map[string]any
}

func (e *Error) Error() string { return fmt.Sprintf("fiducia: HTTP %d", e.Status) }

type Client struct {
	Base string
	HTTP *http.Client
}

func New(base string) *Client { return &Client{Base: base, HTTP: http.DefaultClient} }

func enc(s string) string { return url.QueryEscape(s) }

func merge(dst, src map[string]any) map[string]any {
	for k, v := range src {
		dst[k] = v
	}
	return dst
}

func (c *Client) request(method, path string, body map[string]any) (map[string]any, error) {
	var rdr io.Reader
	if body != nil {
		b, _ := json.Marshal(body)
		rdr = bytes.NewReader(b)
	}
	req, err := http.NewRequest(method, c.Base+path, rdr)
	if err != nil {
		return nil, err
	}
	if body != nil {
		req.Header.Set("content-type", "application/json")
	}
	resp, err := c.HTTP.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(resp.Body)
	var out map[string]any
	if len(raw) > 0 {
		_ = json.Unmarshal(raw, &out)
	}
	if resp.StatusCode >= 400 {
		return nil, &Error{Status: resp.StatusCode, Body: out}
	}
	return out, nil
}

// Health Liveness probe.
func (c *Client) Health() (map[string]any, error) {
	return c.request("GET", "/healthz", nil)
}

// Status Per-shard consensus status.
func (c *Client) Status() (map[string]any, error) {
	return c.request("GET", "/v1/status", nil)
}

// LockGet Inspect a lock member key: holder, the held union, and the FIFO wait queue.
func (c *Client) LockGet(key string) (map[string]any, error) {
	path := fmt.Sprintf("/v1/locks?key=%s", enc(key))
	return c.request("GET", path, nil)
}

// LockAcquire Acquire a single-key lock (try-lock unless wait).
func (c *Client) LockAcquire(key string, opts map[string]any) (map[string]any, error) {
	body := map[string]any{"key": key}
	merge(body, opts)
	return c.request("POST", "/v1/locks/acquire", body)
}

// LockAcquireMany Multi-key UNION lock: all-or-nothing across the set; conflicts on any member key.
func (c *Client) LockAcquireMany(keys []string, opts map[string]any) (map[string]any, error) {
	body := map[string]any{"keys": keys}
	merge(body, opts)
	return c.request("POST", "/v1/locks/acquire", body)
}

// LockRelease Release the whole grant (every member key) by its fencing token.
func (c *Client) LockRelease(holder string, fencingToken int64) (map[string]any, error) {
	body := map[string]any{"holder": holder, "fencing_token": fencingToken}
	return c.request("POST", "/v1/locks/release", body)
}

// SemaphoreGet Inspect a semaphore: limit, holders, free permits, queue.
func (c *Client) SemaphoreGet(key string) (map[string]any, error) {
	path := fmt.Sprintf("/v1/semaphores?key=%s", enc(key))
	return c.request("GET", path, nil)
}

// SemaphoreAcquire Take a permit of a counting semaphore (up to limit holders).
func (c *Client) SemaphoreAcquire(key string, limit int64, opts map[string]any) (map[string]any, error) {
	body := map[string]any{"key": key, "limit": limit}
	merge(body, opts)
	return c.request("POST", "/v1/semaphores/acquire", body)
}

// SemaphoreRelease Return one permit (admits the next FIFO waiter).
func (c *Client) SemaphoreRelease(key string, holder string, fencingToken int64) (map[string]any, error) {
	body := map[string]any{"key": key, "holder": holder, "fencing_token": fencingToken}
	return c.request("POST", "/v1/semaphores/release", body)
}

// IdempotencyGet Inspect an active idempotency record.
func (c *Client) IdempotencyGet(key string) (map[string]any, error) {
	path := fmt.Sprintf("/v1/idempotency?key=%s", enc(key))
	return c.request("GET", path, nil)
}

// IdempotencyClaim Claim an idempotency key; first claimant wins until TTL expiry, duplicates return the existing record.
func (c *Client) IdempotencyClaim(key string, opts map[string]any) (map[string]any, error) {
	body := map[string]any{"key": key}
	merge(body, opts)
	return c.request("POST", "/v1/idempotency/claim", body)
}

// IdempotencyComplete Mark a claimed idempotency key complete and optionally store a replayable result.
func (c *Client) IdempotencyComplete(key string, owner string, fencingToken int64, opts map[string]any) (map[string]any, error) {
	body := map[string]any{"key": key, "owner": owner, "fencing_token": fencingToken}
	merge(body, opts)
	return c.request("POST", "/v1/idempotency/complete", body)
}

// KvGet Read a config key.
func (c *Client) KvGet(key string) (map[string]any, error) {
	path := fmt.Sprintf("/v1/kv?key=%s", enc(key))
	return c.request("GET", path, nil)
}

// KvPut Write a config key; prev_revision is a compare-and-swap guard (0 = must-not-exist).
func (c *Client) KvPut(key string, value string, opts map[string]any) (map[string]any, error) {
	path := fmt.Sprintf("/v1/kv?key=%s", enc(key))
	body := map[string]any{"value": value}
	merge(body, opts)
	return c.request("PUT", path, body)
}

// KvDelete Delete a config key.
func (c *Client) KvDelete(key string) (map[string]any, error) {
	path := fmt.Sprintf("/v1/kv?key=%s", enc(key))
	return c.request("DELETE", path, nil)
}

// CounterGet Read a counter's value and revision; absent reads as found=false (treat as 0).
func (c *Client) CounterGet(key string) (map[string]any, error) {
	path := fmt.Sprintf("/v1/counters?key=%s", enc(key))
	return c.request("GET", path, nil)
}

// CounterAdd Atomically add delta (may be negative); prev_revision makes it a compare-and-set.
func (c *Client) CounterAdd(key string, delta int64, opts map[string]any) (map[string]any, error) {
	body := map[string]any{"key": key, "delta": delta}
	merge(body, opts)
	return c.request("POST", "/v1/counters/add", body)
}

// CounterSet Set a counter to an absolute value (e.g. reset to 0); prev_revision makes it a compare-and-set.
func (c *Client) CounterSet(key string, value int64, opts map[string]any) (map[string]any, error) {
	body := map[string]any{"key": key, "value": value}
	merge(body, opts)
	return c.request("POST", "/v1/counters/set", body)
}

// BarrierGet Read a barrier's arrivals and resolution status; absent reads as found=false.
func (c *Client) BarrierGet(name string) (map[string]any, error) {
	path := fmt.Sprintf("/v1/barriers?name=%s", enc(name))
	return c.request("GET", path, nil)
}

// BarrierCreate Create a fan-in barrier with a resolution policy (all/quorum/first_success/any_veto/best_by_deadline/weighted_quorum).
func (c *Client) BarrierCreate(name string, policy map[string]any, opts map[string]any) (map[string]any, error) {
	body := map[string]any{"name": name, "policy": policy}
	merge(body, opts)
	return c.request("POST", "/v1/barriers/create", body)
}

// BarrierArrive Record a participant's arrival or veto; repeat arrivals by the same participant are idempotent.
func (c *Client) BarrierArrive(name string, participant string, opts map[string]any) (map[string]any, error) {
	body := map[string]any{"name": name, "participant": participant}
	merge(body, opts)
	return c.request("POST", "/v1/barriers/arrive", body)
}

// TaskGet Read a task's status, owner, and fencing token; absent reads as found=false.
func (c *Client) TaskGet(name string) (map[string]any, error) {
	path := fmt.Sprintf("/v1/tasks?name=%s", enc(name))
	return c.request("GET", path, nil)
}

// TaskCreate Create a durable task if it does not exist (idempotent).
func (c *Client) TaskCreate(name string, taskType string, opts map[string]any) (map[string]any, error) {
	body := map[string]any{"name": name, "task_type": taskType}
	merge(body, opts)
	return c.request("POST", "/v1/tasks/create", body)
}

// TaskClaim Claim a pending or lease-expired task; the grant carries a fencing token.
func (c *Client) TaskClaim(name string, worker string, opts map[string]any) (map[string]any, error) {
	body := map[string]any{"name": name, "worker": worker}
	merge(body, opts)
	return c.request("POST", "/v1/tasks/claim", body)
}

// TaskProgress Report progress and a checkpoint under the current fencing token.
func (c *Client) TaskProgress(name string, worker string, fencingToken int64, opts map[string]any) (map[string]any, error) {
	body := map[string]any{"name": name, "worker": worker, "fencing_token": fencingToken}
	merge(body, opts)
	return c.request("POST", "/v1/tasks/progress", body)
}

// TaskComplete Complete a task with a durable result under the current fencing token.
func (c *Client) TaskComplete(name string, worker string, fencingToken int64, opts map[string]any) (map[string]any, error) {
	body := map[string]any{"name": name, "worker": worker, "fencing_token": fencingToken}
	merge(body, opts)
	return c.request("POST", "/v1/tasks/complete", body)
}

// TaskFail Fail a task; retryable requeues it for another worker.
func (c *Client) TaskFail(name string, worker string, fencingToken int64, opts map[string]any) (map[string]any, error) {
	body := map[string]any{"name": name, "worker": worker, "fencing_token": fencingToken}
	merge(body, opts)
	return c.request("POST", "/v1/tasks/fail", body)
}

// TaskCancel Cancel a task (terminal), regardless of owner.
func (c *Client) TaskCancel(name string) (map[string]any, error) {
	body := map[string]any{"name": name}
	return c.request("POST", "/v1/tasks/cancel", body)
}

// EffectGet Read an effect's status, approvals, and result; absent reads as found=false.
func (c *Client) EffectGet(name string) (map[string]any, error) {
	path := fmt.Sprintf("/v1/effects?name=%s", enc(name))
	return c.request("GET", path, nil)
}

// EffectPrepare Prepare a side effect for later authorization (idempotent); required_approvals of 0 is pre-approved.
func (c *Client) EffectPrepare(name string, effectType string, idempotencyKey string, opts map[string]any) (map[string]any, error) {
	body := map[string]any{"name": name, "effect_type": effectType, "idempotency_key": idempotencyKey}
	merge(body, opts)
	return c.request("POST", "/v1/effects/prepare", body)
}

// EffectApprove Record one principal's approval; duplicate approvals count once.
func (c *Client) EffectApprove(name string, principal string) (map[string]any, error) {
	body := map[string]any{"name": name, "principal": principal}
	return c.request("POST", "/v1/effects/approve", body)
}

// EffectCommit Commit an approved effect exactly once, recording the result; a repeat commit replays.
func (c *Client) EffectCommit(name string, opts map[string]any) (map[string]any, error) {
	body := map[string]any{"name": name}
	merge(body, opts)
	return c.request("POST", "/v1/effects/commit", body)
}

// EffectAbort Abort a prepared/approved effect (terminal).
func (c *Client) EffectAbort(name string) (map[string]any, error) {
	body := map[string]any{"name": name}
	return c.request("POST", "/v1/effects/abort", body)
}

// HandoffGet Read a handoff's status, counterparties, and tokens; absent reads as found=false.
func (c *Client) HandoffGet(name string) (map[string]any, error) {
	path := fmt.Sprintf("/v1/handoffs?name=%s", enc(name))
	return c.request("GET", path, nil)
}

// HandoffOffer Offer to transfer ownership of a resource; the original owner keeps authority until accepted.
func (c *Client) HandoffOffer(name string, resource string, from string, to string, fromToken int64, opts map[string]any) (map[string]any, error) {
	body := map[string]any{"name": name, "resource": resource, "from": from, "to": to, "from_token": fromToken}
	merge(body, opts)
	return c.request("POST", "/v1/handoffs/offer", body)
}

// HandoffAccept Accept an offered handoff; the new owner receives a strictly higher fencing token.
func (c *Client) HandoffAccept(name string, to string) (map[string]any, error) {
	body := map[string]any{"name": name, "to": to}
	return c.request("POST", "/v1/handoffs/accept", body)
}

// HandoffReject Reject an offered handoff; ownership stays with the original owner.
func (c *Client) HandoffReject(name string, to string) (map[string]any, error) {
	body := map[string]any{"name": name, "to": to}
	return c.request("POST", "/v1/handoffs/reject", body)
}

// DecisionGet Read a decision's options, tallies, votes, and resolution; absent reads as found=false.
func (c *Client) DecisionGet(name string) (map[string]any, error) {
	path := fmt.Sprintf("/v1/decisions?name=%s", enc(name))
	return c.request("GET", path, nil)
}

// DecisionPropose Propose a decision with typed options and a resolution policy (plurality/threshold/unanimous).
func (c *Client) DecisionPropose(name string, question string, options map[string]any, policy map[string]any, opts map[string]any) (map[string]any, error) {
	body := map[string]any{"name": name, "question": question, "options": options, "policy": policy}
	merge(body, opts)
	return c.request("POST", "/v1/decisions/propose", body)
}

// DecisionVote Cast or replace a vote; option omitted abstains, veto aborts, weight drives resolution.
func (c *Client) DecisionVote(name string, voter string, opts map[string]any) (map[string]any, error) {
	body := map[string]any{"name": name, "voter": voter}
	merge(body, opts)
	return c.request("POST", "/v1/decisions/vote", body)
}

// ElectionGet Observe the current holder of a named election.
func (c *Client) ElectionGet(name string) (map[string]any, error) {
	path := fmt.Sprintf("/v1/elections/%s", enc(name))
	return c.request("GET", path, nil)
}

// ElectionCampaign Campaign for leadership with optional candidate metadata; wins if currently unheld. Returns a fencing token on win.
func (c *Client) ElectionCampaign(name string, candidate string, ttlMs int64, opts map[string]any) (map[string]any, error) {
	path := fmt.Sprintf("/v1/elections/%s/campaign", enc(name))
	body := map[string]any{"candidate": candidate, "ttl_ms": ttlMs}
	merge(body, opts)
	return c.request("POST", path, body)
}

// ElectionRenew Extend the lease; requires the held fencing token.
func (c *Client) ElectionRenew(name string, candidate string, fencingToken int64) (map[string]any, error) {
	path := fmt.Sprintf("/v1/elections/%s/renew", enc(name))
	body := map[string]any{"candidate": candidate, "fencing_token": fencingToken}
	return c.request("POST", path, body)
}

// ElectionResign Step down; requires the held fencing token.
func (c *Client) ElectionResign(name string, candidate string, fencingToken int64) (map[string]any, error) {
	path := fmt.Sprintf("/v1/elections/%s/resign", enc(name))
	body := map[string]any{"candidate": candidate, "fencing_token": fencingToken}
	return c.request("POST", path, body)
}

// ServiceInstances List live instances of a service, optionally filtered by exact metadata matches.
func (c *Client) ServiceInstances(service string, opts map[string]any) (map[string]any, error) {
	path := fmt.Sprintf("/v1/services/%s?metadata=%s", enc(service), enc(metadata))
	return c.request("GET", path, nil)
}

// ServiceRegister Register/refresh an instance with a TTL lease and optional metadata.
func (c *Client) ServiceRegister(service string, instanceId string, address string, ttlMs int64, opts map[string]any) (map[string]any, error) {
	path := fmt.Sprintf("/v1/services/%s/instances/%s", enc(service), enc(instanceId))
	body := map[string]any{"address": address, "ttl_ms": ttlMs}
	merge(body, opts)
	return c.request("PUT", path, body)
}

// ServiceHeartbeat Renew an instance lease before it expires.
func (c *Client) ServiceHeartbeat(service string, instanceId string, opts map[string]any) (map[string]any, error) {
	path := fmt.Sprintf("/v1/services/%s/instances/%s/heartbeat", enc(service), enc(instanceId))
	body := map[string]any{}
	merge(body, opts)
	return c.request("POST", path, body)
}

// ServiceDeregister Remove an instance from the registry.
func (c *Client) ServiceDeregister(service string, instanceId string) (map[string]any, error) {
	path := fmt.Sprintf("/v1/services/%s/instances/%s", enc(service), enc(instanceId))
	return c.request("DELETE", path, nil)
}

// RateLimitGet Current limiter state for a tenant/key.
func (c *Client) RateLimitGet(tenant string, key string) (map[string]any, error) {
	path := fmt.Sprintf("/v1/rate-limit/%s/%s", enc(tenant), enc(key))
	return c.request("GET", path, nil)
}

// RateLimitCheck Atomic check-and-decrement (token_bucket | sliding_window). Returns {allowed, remaining}.
func (c *Client) RateLimitCheck(tenant string, key string, algorithm string, limit int64, windowMs int64, opts map[string]any) (map[string]any, error) {
	path := fmt.Sprintf("/v1/rate-limit/%s/%s/check", enc(tenant), enc(key))
	body := map[string]any{"algorithm": algorithm, "limit": limit, "window_ms": windowMs}
	merge(body, opts)
	return c.request("POST", path, body)
}

// ScheduleGet Read a schedule definition.
func (c *Client) ScheduleGet(name string) (map[string]any, error) {
	path := fmt.Sprintf("/v1/cron/schedules/%s", enc(name))
	return c.request("GET", path, nil)
}

// ScheduleUpsert Create/update a schedule. target = {kind: webhook|queue|grpc, ...}. Exactly one of cron / one_shot_at_ms.
func (c *Client) ScheduleUpsert(name string, target map[string]any, opts map[string]any) (map[string]any, error) {
	path := fmt.Sprintf("/v1/cron/schedules/%s", enc(name))
	body := map[string]any{"target": target}
	merge(body, opts)
	return c.request("PUT", path, body)
}

// ScheduleRecordRun Record a fire; duplicate fire_id is deduped (exactly-once).
func (c *Client) ScheduleRecordRun(name string, fireId string, opts map[string]any) (map[string]any, error) {
	path := fmt.Sprintf("/v1/cron/schedules/%s/runs", enc(name))
	body := map[string]any{"fire_id": fireId}
	merge(body, opts)
	return c.request("POST", path, body)
}

// ScheduleHistory Recent run history.
func (c *Client) ScheduleHistory(name string) (map[string]any, error) {
	path := fmt.Sprintf("/v1/cron/schedules/%s/history", enc(name))
	return c.request("GET", path, nil)
}
