// GENERATED by generate.py from operations.json — DO NOT EDIT BY HAND.
//! Fiducia client (Rust -> WebAssembly) — generated. Browser transport via `fetch`.
//!
//! Build:  wasm-pack build clients/rust-wasm --target web
//!
//! Every operation is an `async` method (exported to JS as camelCase) that
//! resolves to the parsed JSON response, or rejects with `{ status, body }` on a
//! non-2xx response or transport failure.
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use wasm_bindgen_futures::JsFuture;
use web_sys::{Request, RequestInit, Response};

/// URL-encode a path/query segment via the JS `encodeURIComponent`.
fn enc(s: &str) -> String {
    String::from(js_sys::encode_uri_component(s))
}

/// Build the `{ status, body }` rejection value used for every failure.
fn err(status: u16, body: JsValue) -> JsValue {
    let o = js_sys::Object::new();
    let _ = js_sys::Reflect::set(&o, &JsValue::from_str("status"), &JsValue::from(status));
    let _ = js_sys::Reflect::set(&o, &JsValue::from_str("body"), &body);
    o.into()
}

#[wasm_bindgen]
pub struct FiduciaClient {
    base: String,
}

#[wasm_bindgen]
impl FiduciaClient {
    #[wasm_bindgen(constructor)]
    pub fn new(base_url: &str) -> FiduciaClient {
        FiduciaClient { base: base_url.trim_end_matches('/').to_string() }
    }

    async fn request(&self, method: &str, path: String, body: Option<String>) -> Result<JsValue, JsValue> {
        let opts = RequestInit::new();
        opts.set_method(method);
        if let Some(ref b) = body {
            opts.set_body(&JsValue::from_str(b));
        }
        let url = format!("{}{}", self.base, path);
        let request = Request::new_with_str_and_init(&url, &opts).map_err(|e| err(0, e))?;
        if body.is_some() {
            request.headers().set("content-type", "application/json").map_err(|e| err(0, e))?;
        }
        let window = web_sys::window().ok_or_else(|| err(0, JsValue::from_str("no global `window`")))?;
        let resp_value = JsFuture::from(window.fetch_with_request(&request)).await.map_err(|e| err(0, e))?;
        let resp: Response = resp_value.dyn_into().map_err(|e| err(0, e))?;
        let text_value = JsFuture::from(resp.text().map_err(|e| err(0, e))?).await.map_err(|e| err(0, e))?;
        let text = text_value.as_string().unwrap_or_default();
        let parsed = if text.is_empty() {
            JsValue::NULL
        } else {
            js_sys::JSON::parse(&text).unwrap_or(JsValue::NULL)
        };
        if !resp.ok() {
            return Err(err(resp.status(), parsed));
        }
        Ok(parsed)
    }

    /// Liveness probe.
    pub async fn health(&self) -> Result<JsValue, JsValue> {
        let path = String::from("/healthz");
        self.request("GET", path, None).await
    }

    /// Per-shard consensus status.
    pub async fn status(&self) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/status");
        self.request("GET", path, None).await
    }

    /// Inspect a lock member key: holder, the held union, and the FIFO wait queue.
    pub async fn lock_get(&self, key: String) -> Result<JsValue, JsValue> {
        let path = format!("/v1/locks?key={}", enc(&key));
        self.request("GET", path, None).await
    }

    /// Acquire a single-key lock (try-lock unless wait).
    pub async fn lock_acquire(&self, key: String, holder: Option<String>, ttl_ms: Option<i64>, wait: Option<bool>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/locks/acquire");
        let mut _body = serde_json::Map::new();
        _body.insert("key".to_string(), serde_json::Value::String(key));
        if let Some(v) = holder {
            _body.insert("holder".to_string(), serde_json::json!(v));
        }
        if let Some(v) = ttl_ms {
            _body.insert("ttl_ms".to_string(), serde_json::json!(v));
        }
        if let Some(v) = wait {
            _body.insert("wait".to_string(), serde_json::json!(v));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Multi-key UNION lock: all-or-nothing across the set; conflicts on any member key.
    pub async fn lock_acquire_many(&self, keys: Vec<String>, holder: Option<String>, ttl_ms: Option<i64>, wait: Option<bool>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/locks/acquire");
        let mut _body = serde_json::Map::new();
        _body.insert("keys".to_string(), serde_json::json!(keys));
        if let Some(v) = holder {
            _body.insert("holder".to_string(), serde_json::json!(v));
        }
        if let Some(v) = ttl_ms {
            _body.insert("ttl_ms".to_string(), serde_json::json!(v));
        }
        if let Some(v) = wait {
            _body.insert("wait".to_string(), serde_json::json!(v));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Release the whole grant (every member key) by its fencing token.
    pub async fn lock_release(&self, holder: String, fencing_token: i64) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/locks/release");
        let mut _body = serde_json::Map::new();
        _body.insert("holder".to_string(), serde_json::Value::String(holder));
        _body.insert("fencing_token".to_string(), serde_json::json!(fencing_token));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Inspect a semaphore: limit, holders, free permits, queue.
    pub async fn semaphore_get(&self, key: String) -> Result<JsValue, JsValue> {
        let path = format!("/v1/semaphores?key={}", enc(&key));
        self.request("GET", path, None).await
    }

    /// Take a permit of a counting semaphore (up to limit holders).
    pub async fn semaphore_acquire(&self, key: String, limit: i64, holder: Option<String>, ttl_ms: Option<i64>, wait: Option<bool>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/semaphores/acquire");
        let mut _body = serde_json::Map::new();
        _body.insert("key".to_string(), serde_json::Value::String(key));
        _body.insert("limit".to_string(), serde_json::json!(limit));
        if let Some(v) = holder {
            _body.insert("holder".to_string(), serde_json::json!(v));
        }
        if let Some(v) = ttl_ms {
            _body.insert("ttl_ms".to_string(), serde_json::json!(v));
        }
        if let Some(v) = wait {
            _body.insert("wait".to_string(), serde_json::json!(v));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Return one permit (admits the next FIFO waiter).
    pub async fn semaphore_release(&self, key: String, holder: String, fencing_token: i64) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/semaphores/release");
        let mut _body = serde_json::Map::new();
        _body.insert("key".to_string(), serde_json::Value::String(key));
        _body.insert("holder".to_string(), serde_json::Value::String(holder));
        _body.insert("fencing_token".to_string(), serde_json::json!(fencing_token));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Inspect an active idempotency record.
    pub async fn idempotency_get(&self, key: String) -> Result<JsValue, JsValue> {
        let path = format!("/v1/idempotency?key={}", enc(&key));
        self.request("GET", path, None).await
    }

    /// Claim an idempotency key; first claimant wins until TTL expiry, duplicates return the existing record.
    pub async fn idempotency_claim(&self, key: String, owner: Option<String>, ttl_ms: Option<i64>, ttl: Option<String>, metadata: JsValue) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/idempotency/claim");
        let mut _body = serde_json::Map::new();
        _body.insert("key".to_string(), serde_json::Value::String(key));
        if let Some(v) = owner {
            _body.insert("owner".to_string(), serde_json::json!(v));
        }
        if let Some(v) = ttl_ms {
            _body.insert("ttl_ms".to_string(), serde_json::json!(v));
        }
        if let Some(v) = ttl {
            _body.insert("ttl".to_string(), serde_json::json!(v));
        }
        if !metadata.is_null() && !metadata.is_undefined() {
            _body.insert("metadata".to_string(), serde_wasm_bindgen::from_value(metadata).map_err(|e| err(0, e.into()))?);
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Mark a claimed idempotency key complete and optionally store a replayable result.
    pub async fn idempotency_complete(&self, key: String, owner: String, fencing_token: i64, result: JsValue) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/idempotency/complete");
        let mut _body = serde_json::Map::new();
        _body.insert("key".to_string(), serde_json::Value::String(key));
        _body.insert("owner".to_string(), serde_json::Value::String(owner));
        _body.insert("fencing_token".to_string(), serde_json::json!(fencing_token));
        if !result.is_null() && !result.is_undefined() {
            _body.insert("result".to_string(), serde_wasm_bindgen::from_value(result).map_err(|e| err(0, e.into()))?);
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Read a config key.
    pub async fn kv_get(&self, key: String) -> Result<JsValue, JsValue> {
        let path = format!("/v1/kv?key={}", enc(&key));
        self.request("GET", path, None).await
    }

    /// Write a config key; prev_revision is a compare-and-swap guard (0 = must-not-exist).
    pub async fn kv_put(&self, key: String, value: String, ttl_ms: Option<i64>, prev_revision: Option<i64>) -> Result<JsValue, JsValue> {
        let path = format!("/v1/kv?key={}", enc(&key));
        let mut _body = serde_json::Map::new();
        _body.insert("value".to_string(), serde_json::Value::String(value));
        if let Some(v) = ttl_ms {
            _body.insert("ttl_ms".to_string(), serde_json::json!(v));
        }
        if let Some(v) = prev_revision {
            _body.insert("prev_revision".to_string(), serde_json::json!(v));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("PUT", path, Some(_payload)).await
    }

    /// Delete a config key.
    pub async fn kv_delete(&self, key: String) -> Result<JsValue, JsValue> {
        let path = format!("/v1/kv?key={}", enc(&key));
        self.request("DELETE", path, None).await
    }

    /// Observe the current holder of a named election.
    pub async fn election_get(&self, name: String) -> Result<JsValue, JsValue> {
        let path = format!("/v1/elections/{}", enc(&name));
        self.request("GET", path, None).await
    }

    /// Campaign for leadership with optional candidate metadata; wins if currently unheld. Returns a fencing token on win.
    pub async fn election_campaign(&self, name: String, candidate: String, ttl_ms: i64, metadata: JsValue) -> Result<JsValue, JsValue> {
        let path = format!("/v1/elections/{}/campaign", enc(&name));
        let mut _body = serde_json::Map::new();
        _body.insert("candidate".to_string(), serde_json::Value::String(candidate));
        _body.insert("ttl_ms".to_string(), serde_json::json!(ttl_ms));
        if !metadata.is_null() && !metadata.is_undefined() {
            _body.insert("metadata".to_string(), serde_wasm_bindgen::from_value(metadata).map_err(|e| err(0, e.into()))?);
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Extend the lease; requires the held fencing token.
    pub async fn election_renew(&self, name: String, candidate: String, fencing_token: i64) -> Result<JsValue, JsValue> {
        let path = format!("/v1/elections/{}/renew", enc(&name));
        let mut _body = serde_json::Map::new();
        _body.insert("candidate".to_string(), serde_json::Value::String(candidate));
        _body.insert("fencing_token".to_string(), serde_json::json!(fencing_token));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Step down; requires the held fencing token.
    pub async fn election_resign(&self, name: String, candidate: String, fencing_token: i64) -> Result<JsValue, JsValue> {
        let path = format!("/v1/elections/{}/resign", enc(&name));
        let mut _body = serde_json::Map::new();
        _body.insert("candidate".to_string(), serde_json::Value::String(candidate));
        _body.insert("fencing_token".to_string(), serde_json::json!(fencing_token));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// List live instances of a service, optionally filtered by exact metadata matches.
    pub async fn service_instances(&self, service: String, metadata: JsValue) -> Result<JsValue, JsValue> {
        let path = format!("/v1/services/{}?metadata={}", enc(&service), enc(&js_sys::JSON::stringify(&metadata).ok().and_then(|s| s.as_string()).unwrap_or_default()));
        self.request("GET", path, None).await
    }

    /// Register/refresh an instance with a TTL lease and optional metadata.
    pub async fn service_register(&self, service: String, instance_id: String, address: String, ttl_ms: i64, metadata: JsValue) -> Result<JsValue, JsValue> {
        let path = format!("/v1/services/{}/instances/{}", enc(&service), enc(&instance_id));
        let mut _body = serde_json::Map::new();
        _body.insert("address".to_string(), serde_json::Value::String(address));
        _body.insert("ttl_ms".to_string(), serde_json::json!(ttl_ms));
        if !metadata.is_null() && !metadata.is_undefined() {
            _body.insert("metadata".to_string(), serde_wasm_bindgen::from_value(metadata).map_err(|e| err(0, e.into()))?);
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("PUT", path, Some(_payload)).await
    }

    /// Renew an instance lease before it expires.
    pub async fn service_heartbeat(&self, service: String, instance_id: String, ttl_ms: Option<i64>) -> Result<JsValue, JsValue> {
        let path = format!("/v1/services/{}/instances/{}/heartbeat", enc(&service), enc(&instance_id));
        let mut _body = serde_json::Map::new();
        if let Some(v) = ttl_ms {
            _body.insert("ttl_ms".to_string(), serde_json::json!(v));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Remove an instance from the registry.
    pub async fn service_deregister(&self, service: String, instance_id: String) -> Result<JsValue, JsValue> {
        let path = format!("/v1/services/{}/instances/{}", enc(&service), enc(&instance_id));
        self.request("DELETE", path, None).await
    }

    /// Current limiter state for a tenant/key.
    pub async fn rate_limit_get(&self, tenant: String, key: String) -> Result<JsValue, JsValue> {
        let path = format!("/v1/rate-limit/{}/{}", enc(&tenant), enc(&key));
        self.request("GET", path, None).await
    }

    /// Atomic check-and-decrement (token_bucket | sliding_window). Returns {allowed, remaining}.
    pub async fn rate_limit_check(&self, tenant: String, key: String, algorithm: String, limit: i64, window_ms: i64, refill_per_second: Option<f64>, cost: Option<i64>) -> Result<JsValue, JsValue> {
        let path = format!("/v1/rate-limit/{}/{}/check", enc(&tenant), enc(&key));
        let mut _body = serde_json::Map::new();
        _body.insert("algorithm".to_string(), serde_json::Value::String(algorithm));
        _body.insert("limit".to_string(), serde_json::json!(limit));
        _body.insert("window_ms".to_string(), serde_json::json!(window_ms));
        if let Some(v) = refill_per_second {
            _body.insert("refill_per_second".to_string(), serde_json::json!(v));
        }
        if let Some(v) = cost {
            _body.insert("cost".to_string(), serde_json::json!(v));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Read a schedule definition.
    pub async fn schedule_get(&self, name: String) -> Result<JsValue, JsValue> {
        let path = format!("/v1/cron/schedules/{}", enc(&name));
        self.request("GET", path, None).await
    }

    /// Create/update a schedule. target = {kind: webhook|queue|grpc, ...}. Exactly one of cron / one_shot_at_ms.
    pub async fn schedule_upsert(&self, name: String, target: JsValue, cron: Option<String>, one_shot_at_ms: Option<i64>, delivery: Option<String>, max_retries: Option<i64>) -> Result<JsValue, JsValue> {
        let path = format!("/v1/cron/schedules/{}", enc(&name));
        let mut _body = serde_json::Map::new();
        _body.insert("target".to_string(), serde_wasm_bindgen::from_value(target).map_err(|e| err(0, e.into()))?);
        if let Some(v) = cron {
            _body.insert("cron".to_string(), serde_json::json!(v));
        }
        if let Some(v) = one_shot_at_ms {
            _body.insert("one_shot_at_ms".to_string(), serde_json::json!(v));
        }
        if let Some(v) = delivery {
            _body.insert("delivery".to_string(), serde_json::json!(v));
        }
        if let Some(v) = max_retries {
            _body.insert("max_retries".to_string(), serde_json::json!(v));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("PUT", path, Some(_payload)).await
    }

    /// Record a fire; duplicate fire_id is deduped (exactly-once).
    pub async fn schedule_record_run(&self, name: String, fire_id: String, fired_at_ms: Option<i64>) -> Result<JsValue, JsValue> {
        let path = format!("/v1/cron/schedules/{}/runs", enc(&name));
        let mut _body = serde_json::Map::new();
        _body.insert("fire_id".to_string(), serde_json::Value::String(fire_id));
        if let Some(v) = fired_at_ms {
            _body.insert("fired_at_ms".to_string(), serde_json::json!(v));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Recent run history.
    pub async fn schedule_history(&self, name: String) -> Result<JsValue, JsValue> {
        let path = format!("/v1/cron/schedules/{}/history", enc(&name));
        self.request("GET", path, None).await
    }
}
