// GENERATED by generate.py from operations.json — DO NOT EDIT BY HAND.
//! Fiducia client (Rust -> WebAssembly) — generated. Transport is the global
//! `fetch` (browser main thread, Web Workers, and Node 18+/Deno).
//!
//! Build:  wasm-pack build clients/rust-wasm --target web
//!
//! Every operation is an `async` method (exported to JS as camelCase) that
//! resolves to the parsed JSON response, or rejects with `{ status, body }` on a
//! non-2xx response or transport failure. Pass an optional `timeout_ms` to the
//! constructor (or `setTimeoutMs`) to bound each request.
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use wasm_bindgen_futures::JsFuture;
use web_sys::{AbortSignal, Request, RequestInit, Response};

// web-sys (0.3) doesn't bind the `AbortSignal.timeout` static, so bind the
// runtime one directly (available in browsers 2022+, Node 17.3+, and Deno).
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = AbortSignal, js_name = timeout)]
    fn abort_signal_timeout(ms: f64) -> AbortSignal;
}

/// URL-encode a path/query segment via the JS `encodeURIComponent`.
fn enc(s: &str) -> String {
    String::from(js_sys::encode_uri_component(s))
}

/// Build the `{ status, body }` rejection value used for every failure.
fn err(status: u16, body: JsValue) -> JsValue {
    let o = js_sys::Object::new();
    let _ = js_sys::Reflect::set(&o, &JsValue::from_str("status"), &JsValue::from(status));
    let _ = js_sys::Reflect::set(&o, &JsValue::from_str("body"), &body);
    o.into()
}

#[wasm_bindgen]
pub struct FiduciaClient {
    base: String,
    timeout_ms: Option<f64>,
}

#[wasm_bindgen]
impl FiduciaClient {
    /// `timeout_ms` is optional (pass `undefined` for none); when set, each
    /// request aborts after that many milliseconds via `AbortSignal.timeout`.
    #[wasm_bindgen(constructor)]
    pub fn new(base_url: &str, timeout_ms: Option<f64>) -> FiduciaClient {
        FiduciaClient { base: base_url.trim_end_matches('/').to_string(), timeout_ms }
    }

    /// Set (or clear, with `undefined`) the per-request timeout in milliseconds.
    #[wasm_bindgen(js_name = setTimeoutMs)]
    pub fn set_timeout_ms(&mut self, timeout_ms: Option<f64>) {
        self.timeout_ms = timeout_ms;
    }

    async fn request(&self, method: &str, path: String, body: Option<String>) -> Result<JsValue, JsValue> {
        let opts = RequestInit::new();
        opts.set_method(method);
        if let Some(ref b) = body {
            opts.set_body(&JsValue::from_str(b));
        }
        // Bound the request with AbortSignal.timeout (browser/worker/Node18+/Deno).
        if let Some(ms) = self.timeout_ms {
            opts.set_signal(Some(&abort_signal_timeout(ms)));
        }
        let url = format!("{}{}", self.base, path);
        let request = Request::new_with_str_and_init(&url, &opts).map_err(|e| err(0, e))?;
        if body.is_some() {
            request.headers().set("content-type", "application/json").map_err(|e| err(0, e))?;
        }
        // Resolve `fetch` from the global scope so the client works on the
        // browser main thread, in Web Workers, and in Node 18+/Deno (global
        // fetch) — not just `window`.
        let global = js_sys::global();
        let fetch = js_sys::Reflect::get(&global, &JsValue::from_str("fetch"))
            .ok()
            .and_then(|f| f.dyn_into::<js_sys::Function>().ok())
            .ok_or_else(|| err(0, JsValue::from_str("no global fetch available")))?;
        let promise: js_sys::Promise = fetch
            .call1(&global, &request)
            .map_err(|e| err(0, e))?
            .dyn_into()
            .map_err(|e| err(0, e))?;
        let resp_value = JsFuture::from(promise).await.map_err(|e| err(0, e))?;
        let resp: Response = resp_value.dyn_into().map_err(|e| err(0, e))?;
        let text_value = JsFuture::from(resp.text().map_err(|e| err(0, e))?).await.map_err(|e| err(0, e))?;
        let text = text_value.as_string().unwrap_or_default();
        // Parse JSON; if the body isn't JSON, surface the raw text (not null) so
        // non-JSON error pages (proxies, 502s) remain diagnosable.
        let parsed = if text.is_empty() {
            JsValue::NULL
        } else {
            js_sys::JSON::parse(&text).unwrap_or_else(|_| JsValue::from_str(&text))
        };
        if !resp.ok() {
            return Err(err(resp.status(), parsed));
        }
        Ok(parsed)
    }

    /// Liveness probe.
    #[wasm_bindgen(js_name = health)]
    pub async fn health(&self) -> Result<JsValue, JsValue> {
        let path = String::from("/healthz");
        self.request("GET", path, None).await
    }

    /// Per-shard consensus status.
    #[wasm_bindgen(js_name = status)]
    pub async fn status(&self) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/status");
        self.request("GET", path, None).await
    }

    /// Inspect a lock member key: holder, the held union, and the FIFO wait queue.
    #[wasm_bindgen(js_name = lockGet)]
    pub async fn lock_get(&self, key: String) -> Result<JsValue, JsValue> {
        let mut path = String::from("/v1/locks");
        let mut _q: Vec<String> = Vec::new();
        _q.push(format!("key={}", enc(&key)));
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        self.request("GET", path, None).await
    }

    /// Acquire a single-key lock (try-lock unless wait).
    #[wasm_bindgen(js_name = lockAcquire)]
    pub async fn lock_acquire(&self, key: String, holder: Option<String>, ttl_ms: Option<f64>, wait: Option<bool>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/locks/acquire");
        let mut _body = serde_json::Map::new();
        _body.insert("key".to_string(), serde_json::Value::String(key));
        if let Some(v) = holder {
            _body.insert("holder".to_string(), serde_json::json!(v));
        }
        if let Some(v) = ttl_ms {
            _body.insert("ttl_ms".to_string(), serde_json::json!(v as i64));
        }
        if let Some(v) = wait {
            _body.insert("wait".to_string(), serde_json::json!(v));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Multi-key UNION lock: all-or-nothing across the set; conflicts on any member key.
    #[wasm_bindgen(js_name = lockAcquireMany)]
    pub async fn lock_acquire_many(&self, keys: Vec<String>, holder: Option<String>, ttl_ms: Option<f64>, wait: Option<bool>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/locks/acquire");
        let mut _body = serde_json::Map::new();
        _body.insert("keys".to_string(), serde_json::json!(keys));
        if let Some(v) = holder {
            _body.insert("holder".to_string(), serde_json::json!(v));
        }
        if let Some(v) = ttl_ms {
            _body.insert("ttl_ms".to_string(), serde_json::json!(v as i64));
        }
        if let Some(v) = wait {
            _body.insert("wait".to_string(), serde_json::json!(v));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Release the whole grant (every member key) by its fencing token.
    #[wasm_bindgen(js_name = lockRelease)]
    pub async fn lock_release(&self, holder: String, fencing_token: f64) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/locks/release");
        let mut _body = serde_json::Map::new();
        _body.insert("holder".to_string(), serde_json::Value::String(holder));
        _body.insert("fencing_token".to_string(), serde_json::json!(fencing_token as i64));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Inspect a semaphore: limit, holders, free permits, queue.
    #[wasm_bindgen(js_name = semaphoreGet)]
    pub async fn semaphore_get(&self, key: String) -> Result<JsValue, JsValue> {
        let mut path = String::from("/v1/semaphores");
        let mut _q: Vec<String> = Vec::new();
        _q.push(format!("key={}", enc(&key)));
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        self.request("GET", path, None).await
    }

    /// Take a permit of a counting semaphore (up to limit holders).
    #[wasm_bindgen(js_name = semaphoreAcquire)]
    pub async fn semaphore_acquire(&self, key: String, limit: f64, holder: Option<String>, ttl_ms: Option<f64>, wait: Option<bool>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/semaphores/acquire");
        let mut _body = serde_json::Map::new();
        _body.insert("key".to_string(), serde_json::Value::String(key));
        _body.insert("limit".to_string(), serde_json::json!(limit as i64));
        if let Some(v) = holder {
            _body.insert("holder".to_string(), serde_json::json!(v));
        }
        if let Some(v) = ttl_ms {
            _body.insert("ttl_ms".to_string(), serde_json::json!(v as i64));
        }
        if let Some(v) = wait {
            _body.insert("wait".to_string(), serde_json::json!(v));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Return one permit (admits the next FIFO waiter).
    #[wasm_bindgen(js_name = semaphoreRelease)]
    pub async fn semaphore_release(&self, key: String, holder: String, fencing_token: f64) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/semaphores/release");
        let mut _body = serde_json::Map::new();
        _body.insert("key".to_string(), serde_json::Value::String(key));
        _body.insert("holder".to_string(), serde_json::Value::String(holder));
        _body.insert("fencing_token".to_string(), serde_json::json!(fencing_token as i64));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Inspect an active idempotency record.
    #[wasm_bindgen(js_name = idempotencyGet)]
    pub async fn idempotency_get(&self, key: String) -> Result<JsValue, JsValue> {
        let mut path = String::from("/v1/idempotency");
        let mut _q: Vec<String> = Vec::new();
        _q.push(format!("key={}", enc(&key)));
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        self.request("GET", path, None).await
    }

    /// Claim an idempotency key; first claimant wins until TTL expiry, duplicates return the existing record.
    #[wasm_bindgen(js_name = idempotencyClaim)]
    pub async fn idempotency_claim(&self, key: String, owner: Option<String>, ttl_ms: Option<f64>, ttl: Option<String>, metadata: JsValue) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/idempotency/claim");
        let mut _body = serde_json::Map::new();
        _body.insert("key".to_string(), serde_json::Value::String(key));
        if let Some(v) = owner {
            _body.insert("owner".to_string(), serde_json::json!(v));
        }
        if let Some(v) = ttl_ms {
            _body.insert("ttl_ms".to_string(), serde_json::json!(v as i64));
        }
        if let Some(v) = ttl {
            _body.insert("ttl".to_string(), serde_json::json!(v));
        }
        if !metadata.is_null() && !metadata.is_undefined() {
            _body.insert("metadata".to_string(), serde_wasm_bindgen::from_value(metadata).map_err(|e| err(0, e.into()))?);
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Mark a claimed idempotency key complete and optionally store a replayable result.
    #[wasm_bindgen(js_name = idempotencyComplete)]
    pub async fn idempotency_complete(&self, key: String, owner: String, fencing_token: f64, result: JsValue) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/idempotency/complete");
        let mut _body = serde_json::Map::new();
        _body.insert("key".to_string(), serde_json::Value::String(key));
        _body.insert("owner".to_string(), serde_json::Value::String(owner));
        _body.insert("fencing_token".to_string(), serde_json::json!(fencing_token as i64));
        if !result.is_null() && !result.is_undefined() {
            _body.insert("result".to_string(), serde_wasm_bindgen::from_value(result).map_err(|e| err(0, e.into()))?);
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Read a config key.
    #[wasm_bindgen(js_name = kvGet)]
    pub async fn kv_get(&self, key: String) -> Result<JsValue, JsValue> {
        let mut path = String::from("/v1/kv");
        let mut _q: Vec<String> = Vec::new();
        _q.push(format!("key={}", enc(&key)));
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        self.request("GET", path, None).await
    }

    /// Write a config key; prev_revision is a compare-and-swap guard (0 = must-not-exist).
    #[wasm_bindgen(js_name = kvPut)]
    pub async fn kv_put(&self, key: String, value: String, ttl_ms: Option<f64>, prev_revision: Option<f64>) -> Result<JsValue, JsValue> {
        let mut path = String::from("/v1/kv");
        let mut _q: Vec<String> = Vec::new();
        _q.push(format!("key={}", enc(&key)));
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        let mut _body = serde_json::Map::new();
        _body.insert("value".to_string(), serde_json::Value::String(value));
        if let Some(v) = ttl_ms {
            _body.insert("ttl_ms".to_string(), serde_json::json!(v as i64));
        }
        if let Some(v) = prev_revision {
            _body.insert("prev_revision".to_string(), serde_json::json!(v as i64));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("PUT", path, Some(_payload)).await
    }

    /// Delete a config key.
    #[wasm_bindgen(js_name = kvDelete)]
    pub async fn kv_delete(&self, key: String) -> Result<JsValue, JsValue> {
        let mut path = String::from("/v1/kv");
        let mut _q: Vec<String> = Vec::new();
        _q.push(format!("key={}", enc(&key)));
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        self.request("DELETE", path, None).await
    }

    /// Observe the current holder of a named election.
    #[wasm_bindgen(js_name = electionGet)]
    pub async fn election_get(&self, name: String) -> Result<JsValue, JsValue> {
        let path = format!("/v1/elections/{}", enc(&name));
        self.request("GET", path, None).await
    }

    /// Campaign for leadership with optional candidate metadata; wins if currently unheld. Returns a fencing token on win.
    #[wasm_bindgen(js_name = electionCampaign)]
    pub async fn election_campaign(&self, name: String, candidate: String, ttl_ms: f64, metadata: JsValue) -> Result<JsValue, JsValue> {
        let path = format!("/v1/elections/{}/campaign", enc(&name));
        let mut _body = serde_json::Map::new();
        _body.insert("candidate".to_string(), serde_json::Value::String(candidate));
        _body.insert("ttl_ms".to_string(), serde_json::json!(ttl_ms as i64));
        if !metadata.is_null() && !metadata.is_undefined() {
            _body.insert("metadata".to_string(), serde_wasm_bindgen::from_value(metadata).map_err(|e| err(0, e.into()))?);
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Extend the lease; requires the held fencing token.
    #[wasm_bindgen(js_name = electionRenew)]
    pub async fn election_renew(&self, name: String, candidate: String, fencing_token: f64) -> Result<JsValue, JsValue> {
        let path = format!("/v1/elections/{}/renew", enc(&name));
        let mut _body = serde_json::Map::new();
        _body.insert("candidate".to_string(), serde_json::Value::String(candidate));
        _body.insert("fencing_token".to_string(), serde_json::json!(fencing_token as i64));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Step down; requires the held fencing token.
    #[wasm_bindgen(js_name = electionResign)]
    pub async fn election_resign(&self, name: String, candidate: String, fencing_token: f64) -> Result<JsValue, JsValue> {
        let path = format!("/v1/elections/{}/resign", enc(&name));
        let mut _body = serde_json::Map::new();
        _body.insert("candidate".to_string(), serde_json::Value::String(candidate));
        _body.insert("fencing_token".to_string(), serde_json::json!(fencing_token as i64));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// List live instances of a service, optionally filtered by exact metadata matches.
    #[wasm_bindgen(js_name = serviceInstances)]
    pub async fn service_instances(&self, service: String, metadata: JsValue) -> Result<JsValue, JsValue> {
        let mut path = format!("/v1/services/{}", enc(&service));
        let mut _q: Vec<String> = Vec::new();
        if let Some(_obj) = metadata.dyn_ref::<js_sys::Object>() {
            for _entry in js_sys::Object::entries(_obj).iter() {
                let _pair = js_sys::Array::from(&_entry);
                let _k = _pair.get(0).as_string().unwrap_or_default();
                if _k.is_empty() { continue; }
                let _v = _pair.get(1);
                let _vs = _v.as_string().unwrap_or_else(|| js_sys::JSON::stringify(&_v).ok().and_then(|s| s.as_string()).unwrap_or_default());
                _q.push(format!("metadata.{}={}", enc(&_k), enc(&_vs)));
            }
        }
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        self.request("GET", path, None).await
    }

    /// Register/refresh an instance with a TTL lease and optional metadata.
    #[wasm_bindgen(js_name = serviceRegister)]
    pub async fn service_register(&self, service: String, instance_id: String, address: String, ttl_ms: f64, metadata: JsValue) -> Result<JsValue, JsValue> {
        let path = format!("/v1/services/{}/instances/{}", enc(&service), enc(&instance_id));
        let mut _body = serde_json::Map::new();
        _body.insert("address".to_string(), serde_json::Value::String(address));
        _body.insert("ttl_ms".to_string(), serde_json::json!(ttl_ms as i64));
        if !metadata.is_null() && !metadata.is_undefined() {
            _body.insert("metadata".to_string(), serde_wasm_bindgen::from_value(metadata).map_err(|e| err(0, e.into()))?);
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("PUT", path, Some(_payload)).await
    }

    /// Renew an instance lease before it expires.
    #[wasm_bindgen(js_name = serviceHeartbeat)]
    pub async fn service_heartbeat(&self, service: String, instance_id: String, ttl_ms: Option<f64>) -> Result<JsValue, JsValue> {
        let path = format!("/v1/services/{}/instances/{}/heartbeat", enc(&service), enc(&instance_id));
        let mut _body = serde_json::Map::new();
        if let Some(v) = ttl_ms {
            _body.insert("ttl_ms".to_string(), serde_json::json!(v as i64));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Remove an instance from the registry.
    #[wasm_bindgen(js_name = serviceDeregister)]
    pub async fn service_deregister(&self, service: String, instance_id: String) -> Result<JsValue, JsValue> {
        let path = format!("/v1/services/{}/instances/{}", enc(&service), enc(&instance_id));
        self.request("DELETE", path, None).await
    }

    /// Current limiter state for a tenant/key.
    #[wasm_bindgen(js_name = rateLimitGet)]
    pub async fn rate_limit_get(&self, tenant: String, key: String) -> Result<JsValue, JsValue> {
        let path = format!("/v1/rate-limit/{}/{}", enc(&tenant), enc(&key));
        self.request("GET", path, None).await
    }

    /// Atomic check-and-decrement (token_bucket | sliding_window). Returns {allowed, remaining}.
    #[wasm_bindgen(js_name = rateLimitCheck)]
    pub async fn rate_limit_check(&self, tenant: String, key: String, algorithm: String, limit: f64, window_ms: f64, refill_per_second: Option<f64>, cost: Option<f64>) -> Result<JsValue, JsValue> {
        let path = format!("/v1/rate-limit/{}/{}/check", enc(&tenant), enc(&key));
        let mut _body = serde_json::Map::new();
        _body.insert("algorithm".to_string(), serde_json::Value::String(algorithm));
        _body.insert("limit".to_string(), serde_json::json!(limit as i64));
        _body.insert("window_ms".to_string(), serde_json::json!(window_ms as i64));
        if let Some(v) = refill_per_second {
            _body.insert("refill_per_second".to_string(), serde_json::json!(v));
        }
        if let Some(v) = cost {
            _body.insert("cost".to_string(), serde_json::json!(v as i64));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Read a schedule definition.
    #[wasm_bindgen(js_name = scheduleGet)]
    pub async fn schedule_get(&self, name: String) -> Result<JsValue, JsValue> {
        let path = format!("/v1/cron/schedules/{}", enc(&name));
        self.request("GET", path, None).await
    }

    /// Create/update a schedule. target = {kind: webhook|queue|grpc, ...}. Exactly one of cron / one_shot_at_ms.
    #[wasm_bindgen(js_name = scheduleUpsert)]
    pub async fn schedule_upsert(&self, name: String, target: JsValue, cron: Option<String>, one_shot_at_ms: Option<f64>, delivery: Option<String>, max_retries: Option<f64>) -> Result<JsValue, JsValue> {
        let path = format!("/v1/cron/schedules/{}", enc(&name));
        let mut _body = serde_json::Map::new();
        _body.insert("target".to_string(), serde_wasm_bindgen::from_value(target).map_err(|e| err(0, e.into()))?);
        if let Some(v) = cron {
            _body.insert("cron".to_string(), serde_json::json!(v));
        }
        if let Some(v) = one_shot_at_ms {
            _body.insert("one_shot_at_ms".to_string(), serde_json::json!(v as i64));
        }
        if let Some(v) = delivery {
            _body.insert("delivery".to_string(), serde_json::json!(v));
        }
        if let Some(v) = max_retries {
            _body.insert("max_retries".to_string(), serde_json::json!(v as i64));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("PUT", path, Some(_payload)).await
    }

    /// Record a fire; duplicate fire_id is deduped (exactly-once).
    #[wasm_bindgen(js_name = scheduleRecordRun)]
    pub async fn schedule_record_run(&self, name: String, fire_id: String, fired_at_ms: Option<f64>) -> Result<JsValue, JsValue> {
        let path = format!("/v1/cron/schedules/{}/runs", enc(&name));
        let mut _body = serde_json::Map::new();
        _body.insert("fire_id".to_string(), serde_json::Value::String(fire_id));
        if let Some(v) = fired_at_ms {
            _body.insert("fired_at_ms".to_string(), serde_json::json!(v as i64));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Recent run history.
    #[wasm_bindgen(js_name = scheduleHistory)]
    pub async fn schedule_history(&self, name: String) -> Result<JsValue, JsValue> {
        let path = format!("/v1/cron/schedules/{}/history", enc(&name));
        self.request("GET", path, None).await
    }
}
