// GENERATED by generate.py from operations.json — DO NOT EDIT BY HAND.
//! Fiducia client (Rust -> WebAssembly) — generated. Transport is the global
//! `fetch` (browser main thread, Web Workers, and Node 18+/Deno).
//!
//! Build:  wasm-pack build clients/rust-wasm --target web -- --locked
//!
//! Every operation is an `async` method (exported to JS as camelCase) that
//! resolves to the parsed JSON response, or rejects with `{ status, body }` on a
//! non-2xx response or transport failure. Pass an optional `timeout_ms` to the
//! constructor (or `setTimeoutMs`) to bound each request, and `setHeader` to
//! attach default headers such as `Authorization` to every request.
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use wasm_bindgen_futures::JsFuture;
use web_sys::{AbortSignal, Request, RequestInit, RequestRedirect, Response, ResponseType};

// web-sys (0.3) doesn't bind the `AbortSignal.timeout` static, so bind the
// runtime one directly (available in browsers 2022+, Node 17.3+, and Deno).
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = AbortSignal, js_name = timeout)]
    fn abort_signal_timeout(ms: f64) -> AbortSignal;
}

/// URL-encode a path/query segment via the JS `encodeURIComponent`.
fn enc(s: &str) -> String {
    String::from(js_sys::encode_uri_component(s))
}

/// Build the `{ status, body }` rejection value used for every failure.
fn err(status: u16, body: JsValue) -> JsValue {
    let o = js_sys::Object::new();
    let _ = js_sys::Reflect::set(&o, &JsValue::from_str("status"), &JsValue::from(status));
    let _ = js_sys::Reflect::set(&o, &JsValue::from_str("body"), &body);
    o.into()
}

// Integer fields cross JS as f64. Reject values a JSON integer can't faithfully
// represent (NaN/Infinity, fractional, or beyond 2^53) so the client fails loudly
// instead of silently coercing (`NaN as i64` == 0, `Infinity as i64` == i64::MAX).
const MAX_SAFE_INT: f64 = 9_007_199_254_740_991.0;
fn checked_int(v: f64, field: &str) -> Result<i64, JsValue> {
    if !v.is_finite() || v.fract() != 0.0 || v.abs() > MAX_SAFE_INT {
        return Err(err(0, JsValue::from_str(&format!(
            "field `{field}` must be a safe integer, got {v}"
        ))));
    }
    Ok(v as i64)
}

#[wasm_bindgen]
pub struct FiduciaClient {
    base: String,
    timeout_ms: Option<f64>,
    // Default headers applied to every request (e.g. Authorization). Header
    // names are case-insensitive; the last value set for a name wins.
    headers: Vec<(String, String)>,
}

#[wasm_bindgen]
impl FiduciaClient {
    /// `timeout_ms` is optional (pass `undefined` for none); when set, each
    /// request aborts after that many milliseconds via `AbortSignal.timeout`.
    #[wasm_bindgen(constructor)]
    pub fn new(base_url: &str, timeout_ms: Option<f64>) -> FiduciaClient {
        FiduciaClient { base: base_url.trim_end_matches('/').to_string(), timeout_ms, headers: Vec::new() }
    }

    /// Set (or clear, with `undefined`) the per-request timeout in milliseconds.
    #[wasm_bindgen(js_name = setTimeoutMs)]
    pub fn set_timeout_ms(&mut self, timeout_ms: Option<f64>) {
        self.timeout_ms = timeout_ms;
    }

    /// Set a default header sent on every request — e.g. `Authorization`,
    /// `Idempotency-Key`. Setting the same name again replaces it.
    #[wasm_bindgen(js_name = setHeader)]
    pub fn set_header(&mut self, name: &str, value: &str) {
        self.headers.retain(|(n, _)| !n.eq_ignore_ascii_case(name));
        self.headers.push((name.to_string(), value.to_string()));
    }

    /// Remove a previously set default header (no-op if absent).
    #[wasm_bindgen(js_name = removeHeader)]
    pub fn remove_header(&mut self, name: &str) {
        self.headers.retain(|(n, _)| !n.eq_ignore_ascii_case(name));
    }

    async fn request(&self, method: &str, path: String, body: Option<String>) -> Result<JsValue, JsValue> {
        let opts = RequestInit::new();
        opts.set_method(method);
        // Hard-reject redirects: never auto-follow a 3xx, which would replay this
        // (possibly mutating) request and its auth/idempotency headers to an
        // attacker-controlled Location, including an https->http downgrade.
        opts.set_redirect(RequestRedirect::Manual);
        if let Some(ref b) = body {
            opts.set_body(&JsValue::from_str(b));
        }
        // Bound the request with AbortSignal.timeout (browser/worker/Node18+/Deno).
        if let Some(ms) = self.timeout_ms {
            opts.set_signal(Some(&abort_signal_timeout(ms)));
        }
        let url = format!("{}{}", self.base, path);
        let request = Request::new_with_str_and_init(&url, &opts).map_err(|e| err(0, e))?;
        let req_headers = request.headers();
        if body.is_some() {
            req_headers.set("content-type", "application/json").map_err(|e| err(0, e))?;
        }
        // Default headers (auth, idempotency key, ...) override content-type only
        // if the caller explicitly set that name.
        for (name, value) in &self.headers {
            req_headers.set(name, value).map_err(|e| err(0, e))?;
        }
        // Resolve `fetch` from the global scope so the client works on the
        // browser main thread, in Web Workers, and in Node 18+/Deno (global
        // fetch) — not just `window`.
        let global = js_sys::global();
        let fetch = js_sys::Reflect::get(&global, &JsValue::from_str("fetch"))
            .ok()
            .and_then(|f| f.dyn_into::<js_sys::Function>().ok())
            .ok_or_else(|| err(0, JsValue::from_str("no global fetch available")))?;
        let promise: js_sys::Promise = fetch
            .call1(&global, &request)
            .map_err(|e| err(0, e))?
            .dyn_into()
            .map_err(|e| err(0, e))?;
        let resp_value = JsFuture::from(promise).await.map_err(|e| err(0, e))?;
        let resp: Response = resp_value.dyn_into().map_err(|e| err(0, e))?;
        // With redirect:"manual", a redirected fetch yields an opaque-redirect
        // response (status 0) in browsers/workers, or a readable 3xx in Node/Deno.
        // Reject either rather than following it.
        if resp.type_() == ResponseType::Opaqueredirect || (resp.status() >= 300 && resp.status() < 400) {
            return Err(err(resp.status(), JsValue::from_str("fiducia: refusing to follow redirect")));
        }
        let text_value = JsFuture::from(resp.text().map_err(|e| err(0, e))?).await.map_err(|e| err(0, e))?;
        let text = text_value.as_string().unwrap_or_default();
        // Parse JSON; if the body isn't JSON, surface the raw text (not null) so
        // non-JSON error pages (proxies, 502s) remain diagnosable.
        let parsed = if text.is_empty() {
            JsValue::NULL
        } else {
            js_sys::JSON::parse(&text).unwrap_or_else(|_| JsValue::from_str(&text))
        };
        if !resp.ok() {
            return Err(err(resp.status(), parsed));
        }
        Ok(parsed)
    }

    /// Liveness probe.
    #[wasm_bindgen(js_name = health)]
    pub async fn health(&self) -> Result<JsValue, JsValue> {
        let path = String::from("/healthz");
        self.request("GET", path, None).await
    }

    /// Per-shard consensus status.
    #[wasm_bindgen(js_name = status)]
    pub async fn status(&self) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/status");
        self.request("GET", path, None).await
    }

    /// Inspect a lock member key: holder, the held union, and the FIFO wait queue.
    #[wasm_bindgen(js_name = lockGet)]
    pub async fn lock_get(&self, key: String) -> Result<JsValue, JsValue> {
        let mut path = String::from("/v1/locks");
        let mut _q: Vec<String> = Vec::new();
        _q.push(format!("key={}", enc(&key)));
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        self.request("GET", path, None).await
    }

    /// Acquire a single-key lock (try-lock unless wait). holder is required on the wire; SDKs generate one when omitted from their ergonomic API.
    #[wasm_bindgen(js_name = lockAcquire)]
    pub async fn lock_acquire(&self, key: String, holder: String, ttl_ms: Option<f64>, wait: Option<bool>, wait_timeout_ms: Option<f64>, request_id: Option<String>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/locks/acquire");
        let mut _body = serde_json::Map::new();
        _body.insert("key".to_string(), serde_json::Value::String(key));
        _body.insert("holder".to_string(), serde_json::Value::String(holder));
        if let Some(v) = ttl_ms {
            _body.insert("ttl_ms".to_string(), serde_json::json!(checked_int(v, "ttl_ms")?));
        }
        if let Some(v) = wait {
            _body.insert("wait".to_string(), serde_json::json!(v));
        }
        if let Some(v) = wait_timeout_ms {
            _body.insert("wait_timeout_ms".to_string(), serde_json::json!(checked_int(v, "wait_timeout_ms")?));
        }
        if let Some(v) = request_id {
            _body.insert("request_id".to_string(), serde_json::json!(v));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Multi-key UNION lock: all-or-nothing across the set; conflicts on any member key.
    #[wasm_bindgen(js_name = lockAcquireMany)]
    pub async fn lock_acquire_many(&self, keys: Vec<String>, holder: String, ttl_ms: Option<f64>, wait: Option<bool>, wait_timeout_ms: Option<f64>, request_id: Option<String>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/locks/acquire");
        let mut _body = serde_json::Map::new();
        _body.insert("keys".to_string(), serde_json::json!(keys));
        _body.insert("holder".to_string(), serde_json::Value::String(holder));
        if let Some(v) = ttl_ms {
            _body.insert("ttl_ms".to_string(), serde_json::json!(checked_int(v, "ttl_ms")?));
        }
        if let Some(v) = wait {
            _body.insert("wait".to_string(), serde_json::json!(v));
        }
        if let Some(v) = wait_timeout_ms {
            _body.insert("wait_timeout_ms".to_string(), serde_json::json!(checked_int(v, "wait_timeout_ms")?));
        }
        if let Some(v) = request_id {
            _body.insert("request_id".to_string(), serde_json::json!(v));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Renew a held union lock only when holder and fencing token still match; preserves the token.
    #[wasm_bindgen(js_name = lockRenew)]
    pub async fn lock_renew(&self, keys: Vec<String>, holder: String, fencing_token: f64, ttl_ms: f64) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/locks/renew");
        let mut _body = serde_json::Map::new();
        _body.insert("keys".to_string(), serde_json::json!(keys));
        _body.insert("holder".to_string(), serde_json::Value::String(holder));
        _body.insert("fencing_token".to_string(), serde_json::json!(checked_int(fencing_token, "fencing_token")?));
        _body.insert("ttl_ms".to_string(), serde_json::json!(checked_int(ttl_ms, "ttl_ms")?));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Cancel one queued union-lock acquisition attempt. request_id makes a pre-acquire cancel durable and scoped; omitting it preserves the legacy holder/key behavior.
    #[wasm_bindgen(js_name = lockCancel)]
    pub async fn lock_cancel(&self, keys: Vec<String>, holder: String, request_id: Option<String>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/locks/cancel");
        let mut _body = serde_json::Map::new();
        _body.insert("keys".to_string(), serde_json::json!(keys));
        _body.insert("holder".to_string(), serde_json::Value::String(holder));
        if let Some(v) = request_id {
            _body.insert("request_id".to_string(), serde_json::json!(v));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Release the whole grant (every member key) by its fencing token.
    #[wasm_bindgen(js_name = lockRelease)]
    pub async fn lock_release(&self, holder: String, fencing_token: f64) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/locks/release");
        let mut _body = serde_json::Map::new();
        _body.insert("holder".to_string(), serde_json::Value::String(holder));
        _body.insert("fencing_token".to_string(), serde_json::json!(checked_int(fencing_token, "fencing_token")?));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Inspect a semaphore: limit, holders, free permits, queue.
    #[wasm_bindgen(js_name = semaphoreGet)]
    pub async fn semaphore_get(&self, key: String) -> Result<JsValue, JsValue> {
        let mut path = String::from("/v1/semaphores");
        let mut _q: Vec<String> = Vec::new();
        _q.push(format!("key={}", enc(&key)));
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        self.request("GET", path, None).await
    }

    /// Take a permit of a counting semaphore (up to limit holders).
    #[wasm_bindgen(js_name = semaphoreAcquire)]
    pub async fn semaphore_acquire(&self, key: String, limit: f64, holder: String, ttl_ms: Option<f64>, wait: Option<bool>, wait_timeout_ms: Option<f64>, request_id: Option<String>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/semaphores/acquire");
        let mut _body = serde_json::Map::new();
        _body.insert("key".to_string(), serde_json::Value::String(key));
        _body.insert("limit".to_string(), serde_json::json!(checked_int(limit, "limit")?));
        _body.insert("holder".to_string(), serde_json::Value::String(holder));
        if let Some(v) = ttl_ms {
            _body.insert("ttl_ms".to_string(), serde_json::json!(checked_int(v, "ttl_ms")?));
        }
        if let Some(v) = wait {
            _body.insert("wait".to_string(), serde_json::json!(v));
        }
        if let Some(v) = wait_timeout_ms {
            _body.insert("wait_timeout_ms".to_string(), serde_json::json!(checked_int(v, "wait_timeout_ms")?));
        }
        if let Some(v) = request_id {
            _body.insert("request_id".to_string(), serde_json::json!(v));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Renew a held semaphore permit only when holder and fencing token still match; preserves the token.
    #[wasm_bindgen(js_name = semaphoreRenew)]
    pub async fn semaphore_renew(&self, key: String, holder: String, fencing_token: f64, ttl_ms: f64) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/semaphores/renew");
        let mut _body = serde_json::Map::new();
        _body.insert("key".to_string(), serde_json::Value::String(key));
        _body.insert("holder".to_string(), serde_json::Value::String(holder));
        _body.insert("fencing_token".to_string(), serde_json::json!(checked_int(fencing_token, "fencing_token")?));
        _body.insert("ttl_ms".to_string(), serde_json::json!(checked_int(ttl_ms, "ttl_ms")?));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Cancel one queued semaphore acquisition attempt. request_id makes a pre-acquire cancel durable and scoped; omitting it preserves legacy behavior.
    #[wasm_bindgen(js_name = semaphoreCancel)]
    pub async fn semaphore_cancel(&self, key: String, holder: String, request_id: Option<String>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/semaphores/cancel");
        let mut _body = serde_json::Map::new();
        _body.insert("key".to_string(), serde_json::Value::String(key));
        _body.insert("holder".to_string(), serde_json::Value::String(holder));
        if let Some(v) = request_id {
            _body.insert("request_id".to_string(), serde_json::json!(v));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Return one permit (admits the next FIFO waiter).
    #[wasm_bindgen(js_name = semaphoreRelease)]
    pub async fn semaphore_release(&self, key: String, holder: String, fencing_token: f64) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/semaphores/release");
        let mut _body = serde_json::Map::new();
        _body.insert("key".to_string(), serde_json::Value::String(key));
        _body.insert("holder".to_string(), serde_json::Value::String(holder));
        _body.insert("fencing_token".to_string(), serde_json::json!(checked_int(fencing_token, "fencing_token")?));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Inspect an active idempotency record.
    #[wasm_bindgen(js_name = idempotencyGet)]
    pub async fn idempotency_get(&self, key: String) -> Result<JsValue, JsValue> {
        let mut path = String::from("/v1/idempotency");
        let mut _q: Vec<String> = Vec::new();
        _q.push(format!("key={}", enc(&key)));
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        self.request("GET", path, None).await
    }

    /// Claim an idempotency key; first claimant wins until TTL expiry, duplicates return the existing record.
    #[wasm_bindgen(js_name = idempotencyClaim)]
    pub async fn idempotency_claim(&self, key: String, owner: Option<String>, ttl_ms: Option<f64>, ttl: Option<String>, metadata: JsValue) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/idempotency/claim");
        let mut _body = serde_json::Map::new();
        _body.insert("key".to_string(), serde_json::Value::String(key));
        if let Some(v) = owner {
            _body.insert("owner".to_string(), serde_json::json!(v));
        }
        if let Some(v) = ttl_ms {
            _body.insert("ttl_ms".to_string(), serde_json::json!(checked_int(v, "ttl_ms")?));
        }
        if let Some(v) = ttl {
            _body.insert("ttl".to_string(), serde_json::json!(v));
        }
        if !metadata.is_null() && !metadata.is_undefined() {
            _body.insert("metadata".to_string(), serde_wasm_bindgen::from_value(metadata).map_err(|e| err(0, e.into()))?);
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Mark a claimed idempotency key complete and optionally store a replayable result.
    #[wasm_bindgen(js_name = idempotencyComplete)]
    pub async fn idempotency_complete(&self, key: String, owner: String, fencing_token: f64, result: JsValue) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/idempotency/complete");
        let mut _body = serde_json::Map::new();
        _body.insert("key".to_string(), serde_json::Value::String(key));
        _body.insert("owner".to_string(), serde_json::Value::String(owner));
        _body.insert("fencing_token".to_string(), serde_json::json!(checked_int(fencing_token, "fencing_token")?));
        if !result.is_null() && !result.is_undefined() {
            _body.insert("result".to_string(), serde_wasm_bindgen::from_value(result).map_err(|e| err(0, e.into()))?);
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Read a config key.
    #[wasm_bindgen(js_name = kvGet)]
    pub async fn kv_get(&self, key: String) -> Result<JsValue, JsValue> {
        let mut path = String::from("/v1/kv");
        let mut _q: Vec<String> = Vec::new();
        _q.push(format!("key={}", enc(&key)));
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        self.request("GET", path, None).await
    }

    /// Write a config key; values are encrypted at rest when the cluster has KV protection configured. plaintext=true explicitly opts this value out. prev_revision is a compare-and-swap guard (0 = must-not-exist).
    #[wasm_bindgen(js_name = kvPut)]
    pub async fn kv_put(&self, key: String, value: String, ttl_ms: Option<f64>, prev_revision: Option<f64>, plaintext: Option<bool>) -> Result<JsValue, JsValue> {
        let mut path = String::from("/v1/kv");
        let mut _q: Vec<String> = Vec::new();
        _q.push(format!("key={}", enc(&key)));
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        let mut _body = serde_json::Map::new();
        _body.insert("value".to_string(), serde_json::Value::String(value));
        if let Some(v) = ttl_ms {
            _body.insert("ttl_ms".to_string(), serde_json::json!(checked_int(v, "ttl_ms")?));
        }
        if let Some(v) = prev_revision {
            _body.insert("prev_revision".to_string(), serde_json::json!(checked_int(v, "prev_revision")?));
        }
        if let Some(v) = plaintext {
            _body.insert("plaintext".to_string(), serde_json::json!(v));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("PUT", path, Some(_payload)).await
    }

    /// Delete a config key.
    #[wasm_bindgen(js_name = kvDelete)]
    pub async fn kv_delete(&self, key: String) -> Result<JsValue, JsValue> {
        let mut path = String::from("/v1/kv");
        let mut _q: Vec<String> = Vec::new();
        _q.push(format!("key={}", enc(&key)));
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        self.request("DELETE", path, None).await
    }

    /// Read a counter's value and revision; absent reads as found=false (treat as 0).
    #[wasm_bindgen(js_name = counterGet)]
    pub async fn counter_get(&self, key: String) -> Result<JsValue, JsValue> {
        let mut path = String::from("/v1/counters");
        let mut _q: Vec<String> = Vec::new();
        _q.push(format!("key={}", enc(&key)));
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        self.request("GET", path, None).await
    }

    /// Atomically add delta (may be negative); prev_revision makes it a compare-and-set.
    #[wasm_bindgen(js_name = counterAdd)]
    pub async fn counter_add(&self, key: String, delta: f64, prev_revision: Option<f64>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/counters/add");
        let mut _body = serde_json::Map::new();
        _body.insert("key".to_string(), serde_json::Value::String(key));
        _body.insert("delta".to_string(), serde_json::json!(checked_int(delta, "delta")?));
        if let Some(v) = prev_revision {
            _body.insert("prev_revision".to_string(), serde_json::json!(checked_int(v, "prev_revision")?));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Set a counter to an absolute value (e.g. reset to 0); prev_revision makes it a compare-and-set.
    #[wasm_bindgen(js_name = counterSet)]
    pub async fn counter_set(&self, key: String, value: f64, prev_revision: Option<f64>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/counters/set");
        let mut _body = serde_json::Map::new();
        _body.insert("key".to_string(), serde_json::Value::String(key));
        _body.insert("value".to_string(), serde_json::json!(checked_int(value, "value")?));
        if let Some(v) = prev_revision {
            _body.insert("prev_revision".to_string(), serde_json::json!(checked_int(v, "prev_revision")?));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Read a barrier's arrivals and resolution status; absent reads as found=false.
    #[wasm_bindgen(js_name = barrierGet)]
    pub async fn barrier_get(&self, name: String) -> Result<JsValue, JsValue> {
        let mut path = String::from("/v1/barriers");
        let mut _q: Vec<String> = Vec::new();
        _q.push(format!("name={}", enc(&name)));
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        self.request("GET", path, None).await
    }

    /// Create a fan-in barrier with a resolution policy (all/quorum/first_success/any_veto/best_by_deadline/weighted_quorum).
    #[wasm_bindgen(js_name = barrierCreate)]
    pub async fn barrier_create(&self, name: String, policy: JsValue, expected: Option<f64>, deadline_ms: Option<f64>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/barriers/create");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("policy".to_string(), serde_wasm_bindgen::from_value(policy).map_err(|e| err(0, e.into()))?);
        if let Some(v) = expected {
            _body.insert("expected".to_string(), serde_json::json!(checked_int(v, "expected")?));
        }
        if let Some(v) = deadline_ms {
            _body.insert("deadline_ms".to_string(), serde_json::json!(checked_int(v, "deadline_ms")?));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Record a participant's arrival or veto; repeat arrivals by the same participant are idempotent.
    #[wasm_bindgen(js_name = barrierArrive)]
    pub async fn barrier_arrive(&self, name: String, participant: String, weight: Option<f64>, veto: Option<bool>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/barriers/arrive");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("participant".to_string(), serde_json::Value::String(participant));
        if let Some(v) = weight {
            _body.insert("weight".to_string(), serde_json::json!(checked_int(v, "weight")?));
        }
        if let Some(v) = veto {
            _body.insert("veto".to_string(), serde_json::json!(v));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Read a task's status, owner, and fencing token; absent reads as found=false.
    #[wasm_bindgen(js_name = taskGet)]
    pub async fn task_get(&self, name: String) -> Result<JsValue, JsValue> {
        let mut path = String::from("/v1/tasks");
        let mut _q: Vec<String> = Vec::new();
        _q.push(format!("name={}", enc(&name)));
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        self.request("GET", path, None).await
    }

    /// Create a durable task if it does not exist (idempotent).
    #[wasm_bindgen(js_name = taskCreate)]
    pub async fn task_create(&self, name: String, task_type: String, payload: JsValue, deadline_ms: Option<f64>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/tasks/create");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("task_type".to_string(), serde_json::Value::String(task_type));
        if !payload.is_null() && !payload.is_undefined() {
            _body.insert("payload".to_string(), serde_wasm_bindgen::from_value(payload).map_err(|e| err(0, e.into()))?);
        }
        if let Some(v) = deadline_ms {
            _body.insert("deadline_ms".to_string(), serde_json::json!(checked_int(v, "deadline_ms")?));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Claim a pending or lease-expired task; the grant carries a fencing token.
    #[wasm_bindgen(js_name = taskClaim)]
    pub async fn task_claim(&self, name: String, worker: String, ttl_ms: Option<f64>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/tasks/claim");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("worker".to_string(), serde_json::Value::String(worker));
        if let Some(v) = ttl_ms {
            _body.insert("ttl_ms".to_string(), serde_json::json!(checked_int(v, "ttl_ms")?));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Report progress and a checkpoint under the current fencing token.
    #[wasm_bindgen(js_name = taskProgress)]
    pub async fn task_progress(&self, name: String, worker: String, fencing_token: f64, percent: Option<f64>, checkpoint: JsValue) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/tasks/progress");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("worker".to_string(), serde_json::Value::String(worker));
        _body.insert("fencing_token".to_string(), serde_json::json!(checked_int(fencing_token, "fencing_token")?));
        if let Some(v) = percent {
            _body.insert("percent".to_string(), serde_json::json!(checked_int(v, "percent")?));
        }
        if !checkpoint.is_null() && !checkpoint.is_undefined() {
            _body.insert("checkpoint".to_string(), serde_wasm_bindgen::from_value(checkpoint).map_err(|e| err(0, e.into()))?);
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Complete a task with a durable result under the current fencing token.
    #[wasm_bindgen(js_name = taskComplete)]
    pub async fn task_complete(&self, name: String, worker: String, fencing_token: f64, result: JsValue) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/tasks/complete");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("worker".to_string(), serde_json::Value::String(worker));
        _body.insert("fencing_token".to_string(), serde_json::json!(checked_int(fencing_token, "fencing_token")?));
        if !result.is_null() && !result.is_undefined() {
            _body.insert("result".to_string(), serde_wasm_bindgen::from_value(result).map_err(|e| err(0, e.into()))?);
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Fail a task; retryable requeues it for another worker.
    #[wasm_bindgen(js_name = taskFail)]
    pub async fn task_fail(&self, name: String, worker: String, fencing_token: f64, retryable: Option<bool>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/tasks/fail");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("worker".to_string(), serde_json::Value::String(worker));
        _body.insert("fencing_token".to_string(), serde_json::json!(checked_int(fencing_token, "fencing_token")?));
        if let Some(v) = retryable {
            _body.insert("retryable".to_string(), serde_json::json!(v));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Cancel a task (terminal), regardless of owner.
    #[wasm_bindgen(js_name = taskCancel)]
    pub async fn task_cancel(&self, name: String) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/tasks/cancel");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Read an effect's status, approvals, and result; absent reads as found=false.
    #[wasm_bindgen(js_name = effectGet)]
    pub async fn effect_get(&self, name: String) -> Result<JsValue, JsValue> {
        let mut path = String::from("/v1/effects");
        let mut _q: Vec<String> = Vec::new();
        _q.push(format!("name={}", enc(&name)));
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        self.request("GET", path, None).await
    }

    /// Prepare a side effect for later authorization (idempotent); required_approvals of 0 is pre-approved.
    #[wasm_bindgen(js_name = effectPrepare)]
    pub async fn effect_prepare(&self, name: String, effect_type: String, idempotency_key: String, payload: JsValue, risk: Option<String>, required_approvals: Option<f64>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/effects/prepare");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("effect_type".to_string(), serde_json::Value::String(effect_type));
        if !payload.is_null() && !payload.is_undefined() {
            _body.insert("payload".to_string(), serde_wasm_bindgen::from_value(payload).map_err(|e| err(0, e.into()))?);
        }
        if let Some(v) = risk {
            _body.insert("risk".to_string(), serde_json::json!(v));
        }
        _body.insert("idempotency_key".to_string(), serde_json::Value::String(idempotency_key));
        if let Some(v) = required_approvals {
            _body.insert("required_approvals".to_string(), serde_json::json!(checked_int(v, "required_approvals")?));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Record one principal's approval; duplicate approvals count once.
    #[wasm_bindgen(js_name = effectApprove)]
    pub async fn effect_approve(&self, name: String, principal: String) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/effects/approve");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("principal".to_string(), serde_json::Value::String(principal));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Commit an approved effect exactly once, recording the result; a repeat commit replays.
    #[wasm_bindgen(js_name = effectCommit)]
    pub async fn effect_commit(&self, name: String, result: JsValue) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/effects/commit");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        if !result.is_null() && !result.is_undefined() {
            _body.insert("result".to_string(), serde_wasm_bindgen::from_value(result).map_err(|e| err(0, e.into()))?);
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Abort a prepared/approved effect (terminal).
    #[wasm_bindgen(js_name = effectAbort)]
    pub async fn effect_abort(&self, name: String) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/effects/abort");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Read a handoff's status, counterparties, and tokens; absent reads as found=false.
    #[wasm_bindgen(js_name = handoffGet)]
    pub async fn handoff_get(&self, name: String) -> Result<JsValue, JsValue> {
        let mut path = String::from("/v1/handoffs");
        let mut _q: Vec<String> = Vec::new();
        _q.push(format!("name={}", enc(&name)));
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        self.request("GET", path, None).await
    }

    /// Offer to transfer ownership of a resource; the original owner keeps authority until accepted.
    #[wasm_bindgen(js_name = handoffOffer)]
    pub async fn handoff_offer(&self, name: String, resource: String, from: String, to: String, from_token: f64, context: JsValue, ttl_ms: Option<f64>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/handoffs/offer");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("resource".to_string(), serde_json::Value::String(resource));
        _body.insert("from".to_string(), serde_json::Value::String(from));
        _body.insert("to".to_string(), serde_json::Value::String(to));
        _body.insert("from_token".to_string(), serde_json::json!(checked_int(from_token, "from_token")?));
        if !context.is_null() && !context.is_undefined() {
            _body.insert("context".to_string(), serde_wasm_bindgen::from_value(context).map_err(|e| err(0, e.into()))?);
        }
        if let Some(v) = ttl_ms {
            _body.insert("ttl_ms".to_string(), serde_json::json!(checked_int(v, "ttl_ms")?));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Accept an offered handoff; the new owner receives a strictly higher fencing token.
    #[wasm_bindgen(js_name = handoffAccept)]
    pub async fn handoff_accept(&self, name: String, to: String) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/handoffs/accept");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("to".to_string(), serde_json::Value::String(to));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Reject an offered handoff; ownership stays with the original owner.
    #[wasm_bindgen(js_name = handoffReject)]
    pub async fn handoff_reject(&self, name: String, to: String) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/handoffs/reject");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("to".to_string(), serde_json::Value::String(to));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Read a decision's options, tallies, votes, and resolution; absent reads as found=false.
    #[wasm_bindgen(js_name = decisionGet)]
    pub async fn decision_get(&self, name: String) -> Result<JsValue, JsValue> {
        let mut path = String::from("/v1/decisions");
        let mut _q: Vec<String> = Vec::new();
        _q.push(format!("name={}", enc(&name)));
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        self.request("GET", path, None).await
    }

    /// Propose a decision with typed options and a resolution policy (plurality/threshold/unanimous).
    #[wasm_bindgen(js_name = decisionPropose)]
    pub async fn decision_propose(&self, name: String, question: String, options: JsValue, policy: JsValue, deadline_ms: Option<f64>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/decisions/propose");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("question".to_string(), serde_json::Value::String(question));
        _body.insert("options".to_string(), serde_wasm_bindgen::from_value(options).map_err(|e| err(0, e.into()))?);
        _body.insert("policy".to_string(), serde_wasm_bindgen::from_value(policy).map_err(|e| err(0, e.into()))?);
        if let Some(v) = deadline_ms {
            _body.insert("deadline_ms".to_string(), serde_json::json!(checked_int(v, "deadline_ms")?));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Cast or replace a vote; option omitted abstains, veto aborts, weight drives resolution.
    #[wasm_bindgen(js_name = decisionVote)]
    pub async fn decision_vote(&self, name: String, voter: String, option: Option<String>, confidence: Option<f64>, weight: Option<f64>, veto: Option<bool>, evidence: JsValue) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/decisions/vote");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("voter".to_string(), serde_json::Value::String(voter));
        if let Some(v) = option {
            _body.insert("option".to_string(), serde_json::json!(v));
        }
        if let Some(v) = confidence {
            _body.insert("confidence".to_string(), serde_json::json!(v));
        }
        if let Some(v) = weight {
            _body.insert("weight".to_string(), serde_json::json!(checked_int(v, "weight")?));
        }
        if let Some(v) = veto {
            _body.insert("veto".to_string(), serde_json::json!(v));
        }
        if !evidence.is_null() && !evidence.is_undefined() {
            _body.insert("evidence".to_string(), serde_wasm_bindgen::from_value(evidence).map_err(|e| err(0, e.into()))?);
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Read a budget's ceiling, reserved, spent, available, and reservations; absent reads as found=false.
    #[wasm_bindgen(js_name = budgetGet)]
    pub async fn budget_get(&self, name: String) -> Result<JsValue, JsValue> {
        let mut path = String::from("/v1/budgets");
        let mut _q: Vec<String> = Vec::new();
        _q.push(format!("name={}", enc(&name)));
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        self.request("GET", path, None).await
    }

    /// Create or re-cap a budget with a per-axis ceiling (usd_micros, tokens, tool_calls); unset axis is unlimited.
    #[wasm_bindgen(js_name = budgetSet)]
    pub async fn budget_set(&self, name: String, limit: JsValue) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/budgets/set");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("limit".to_string(), serde_wasm_bindgen::from_value(limit).map_err(|e| err(0, e.into()))?);
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Reserve an amount; rejected if it would exceed any limited axis (prevents oversubscription).
    #[wasm_bindgen(js_name = budgetReserve)]
    pub async fn budget_reserve(&self, name: String, reservation_id: String, holder: String, amount: JsValue) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/budgets/reserve");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("reservation_id".to_string(), serde_json::Value::String(reservation_id));
        _body.insert("holder".to_string(), serde_json::Value::String(holder));
        _body.insert("amount".to_string(), serde_wasm_bindgen::from_value(amount).map_err(|e| err(0, e.into()))?);
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Commit a reservation with the actual spend (capped at reserved); frees the difference.
    #[wasm_bindgen(js_name = budgetCommit)]
    pub async fn budget_commit(&self, name: String, reservation_id: String, actual: JsValue) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/budgets/commit");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("reservation_id".to_string(), serde_json::Value::String(reservation_id));
        _body.insert("actual".to_string(), serde_wasm_bindgen::from_value(actual).map_err(|e| err(0, e.into()))?);
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Release a still-held reservation, returning its full headroom.
    #[wasm_bindgen(js_name = budgetRelease)]
    pub async fn budget_release(&self, name: String, reservation_id: String) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/budgets/release");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("reservation_id".to_string(), serde_json::Value::String(reservation_id));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Read a claim's subject/predicate/value, status, support, and contests; absent reads as found=false.
    #[wasm_bindgen(js_name = claimGet)]
    pub async fn claim_get(&self, name: String) -> Result<JsValue, JsValue> {
        let mut path = String::from("/v1/claims");
        let mut _q: Vec<String> = Vec::new();
        _q.push(format!("name={}", enc(&name)));
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        self.request("GET", path, None).await
    }

    /// Assert or re-assert a versioned claim; re-asserting bumps the version and resets support/contests.
    #[wasm_bindgen(js_name = claimAssert)]
    pub async fn claim_assert(&self, name: String, subject: String, predicate: String, author: String, value: JsValue, confidence: Option<f64>, evidence: JsValue, valid_until_ms: Option<f64>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/claims/assert");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("subject".to_string(), serde_json::Value::String(subject));
        _body.insert("predicate".to_string(), serde_json::Value::String(predicate));
        if !value.is_null() && !value.is_undefined() {
            _body.insert("value".to_string(), serde_wasm_bindgen::from_value(value).map_err(|e| err(0, e.into()))?);
        }
        if let Some(v) = confidence {
            _body.insert("confidence".to_string(), serde_json::json!(v));
        }
        _body.insert("author".to_string(), serde_json::Value::String(author));
        if !evidence.is_null() && !evidence.is_undefined() {
            _body.insert("evidence".to_string(), serde_wasm_bindgen::from_value(evidence).map_err(|e| err(0, e.into()))?);
        }
        if let Some(v) = valid_until_ms {
            _body.insert("valid_until_ms".to_string(), serde_json::json!(checked_int(v, "valid_until_ms")?));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Record an agent's support for a claim.
    #[wasm_bindgen(js_name = claimSupport)]
    pub async fn claim_support(&self, name: String, agent: String) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/claims/support");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("agent".to_string(), serde_json::Value::String(agent));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Record an agent's contest of a claim, moving it to contested.
    #[wasm_bindgen(js_name = claimContest)]
    pub async fn claim_contest(&self, name: String, agent: String, reason: Option<String>) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/claims/contest");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("agent".to_string(), serde_json::Value::String(agent));
        if let Some(v) = reason {
            _body.insert("reason".to_string(), serde_json::json!(v));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Authoritatively accept or reject a claim (terminal).
    #[wasm_bindgen(js_name = claimResolve)]
    pub async fn claim_resolve(&self, name: String, accepted: bool) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/claims/resolve");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("accepted".to_string(), serde_json::json!(accepted));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Supersede a claim with a newer one (terminal).
    #[wasm_bindgen(js_name = claimSupersede)]
    pub async fn claim_supersede(&self, name: String, superseded_by: String) -> Result<JsValue, JsValue> {
        let path = String::from("/v1/claims/supersede");
        let mut _body = serde_json::Map::new();
        _body.insert("name".to_string(), serde_json::Value::String(name));
        _body.insert("superseded_by".to_string(), serde_json::Value::String(superseded_by));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Observe the current holder of a named election.
    #[wasm_bindgen(js_name = electionGet)]
    pub async fn election_get(&self, name: String) -> Result<JsValue, JsValue> {
        let path = format!("/v1/elections/{}", enc(&name));
        self.request("GET", path, None).await
    }

    /// Campaign for leadership with optional candidate metadata; wins if currently unheld. Returns a fencing token on win.
    #[wasm_bindgen(js_name = electionCampaign)]
    pub async fn election_campaign(&self, name: String, candidate: String, ttl_ms: f64, metadata: JsValue) -> Result<JsValue, JsValue> {
        let path = format!("/v1/elections/{}/campaign", enc(&name));
        let mut _body = serde_json::Map::new();
        _body.insert("candidate".to_string(), serde_json::Value::String(candidate));
        _body.insert("ttl_ms".to_string(), serde_json::json!(checked_int(ttl_ms, "ttl_ms")?));
        if !metadata.is_null() && !metadata.is_undefined() {
            _body.insert("metadata".to_string(), serde_wasm_bindgen::from_value(metadata).map_err(|e| err(0, e.into()))?);
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Extend the lease; requires the held fencing token.
    #[wasm_bindgen(js_name = electionRenew)]
    pub async fn election_renew(&self, name: String, candidate: String, fencing_token: f64) -> Result<JsValue, JsValue> {
        let path = format!("/v1/elections/{}/renew", enc(&name));
        let mut _body = serde_json::Map::new();
        _body.insert("candidate".to_string(), serde_json::Value::String(candidate));
        _body.insert("fencing_token".to_string(), serde_json::json!(checked_int(fencing_token, "fencing_token")?));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Step down; requires the held fencing token.
    #[wasm_bindgen(js_name = electionResign)]
    pub async fn election_resign(&self, name: String, candidate: String, fencing_token: f64) -> Result<JsValue, JsValue> {
        let path = format!("/v1/elections/{}/resign", enc(&name));
        let mut _body = serde_json::Map::new();
        _body.insert("candidate".to_string(), serde_json::Value::String(candidate));
        _body.insert("fencing_token".to_string(), serde_json::json!(checked_int(fencing_token, "fencing_token")?));
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// List live instances of a service, optionally filtered by exact metadata matches.
    #[wasm_bindgen(js_name = serviceInstances)]
    pub async fn service_instances(&self, service: String, metadata: JsValue) -> Result<JsValue, JsValue> {
        let mut path = format!("/v1/services/{}", enc(&service));
        let mut _q: Vec<String> = Vec::new();
        if let Some(_obj) = metadata.dyn_ref::<js_sys::Object>() {
            for _entry in js_sys::Object::entries(_obj).iter() {
                let _pair = js_sys::Array::from(&_entry);
                let _k = _pair.get(0).as_string().unwrap_or_default();
                if _k.is_empty() { continue; }
                let _v = _pair.get(1);
                let _vs = match _v.as_string() {
                    Some(_s) => _s,
                    None => return Err(err(0, JsValue::from_str(&format!("metadata.{_k} must be a string")))),
                };
                _q.push(format!("metadata.{}={}", enc(&_k), enc(&_vs)));
            }
        }
        if !_q.is_empty() {
            path.push('?');
            path.push_str(&_q.join("&"));
        }
        self.request("GET", path, None).await
    }

    /// Register/refresh an instance with a TTL lease and optional metadata.
    #[wasm_bindgen(js_name = serviceRegister)]
    pub async fn service_register(&self, service: String, instance_id: String, address: String, ttl_ms: f64, metadata: JsValue) -> Result<JsValue, JsValue> {
        let path = format!("/v1/services/{}/instances/{}", enc(&service), enc(&instance_id));
        let mut _body = serde_json::Map::new();
        _body.insert("address".to_string(), serde_json::Value::String(address));
        _body.insert("ttl_ms".to_string(), serde_json::json!(checked_int(ttl_ms, "ttl_ms")?));
        if !metadata.is_null() && !metadata.is_undefined() {
            _body.insert("metadata".to_string(), serde_wasm_bindgen::from_value(metadata).map_err(|e| err(0, e.into()))?);
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("PUT", path, Some(_payload)).await
    }

    /// Renew an instance lease before it expires.
    #[wasm_bindgen(js_name = serviceHeartbeat)]
    pub async fn service_heartbeat(&self, service: String, instance_id: String, ttl_ms: Option<f64>) -> Result<JsValue, JsValue> {
        let path = format!("/v1/services/{}/instances/{}/heartbeat", enc(&service), enc(&instance_id));
        let mut _body = serde_json::Map::new();
        if let Some(v) = ttl_ms {
            _body.insert("ttl_ms".to_string(), serde_json::json!(checked_int(v, "ttl_ms")?));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Remove an instance from the registry.
    #[wasm_bindgen(js_name = serviceDeregister)]
    pub async fn service_deregister(&self, service: String, instance_id: String) -> Result<JsValue, JsValue> {
        let path = format!("/v1/services/{}/instances/{}", enc(&service), enc(&instance_id));
        self.request("DELETE", path, None).await
    }

    /// Current limiter state for a tenant/key.
    #[wasm_bindgen(js_name = rateLimitGet)]
    pub async fn rate_limit_get(&self, tenant: String, key: String) -> Result<JsValue, JsValue> {
        let path = format!("/v1/rate-limit/{}/{}", enc(&tenant), enc(&key));
        self.request("GET", path, None).await
    }

    /// Atomic check-and-decrement (token_bucket | sliding_window). Returns {allowed, remaining}.
    #[wasm_bindgen(js_name = rateLimitCheck)]
    pub async fn rate_limit_check(&self, tenant: String, key: String, algorithm: String, limit: f64, window_ms: f64, refill_per_second: Option<f64>, cost: Option<f64>) -> Result<JsValue, JsValue> {
        let path = format!("/v1/rate-limit/{}/{}/check", enc(&tenant), enc(&key));
        let mut _body = serde_json::Map::new();
        _body.insert("algorithm".to_string(), serde_json::Value::String(algorithm));
        _body.insert("limit".to_string(), serde_json::json!(checked_int(limit, "limit")?));
        _body.insert("window_ms".to_string(), serde_json::json!(checked_int(window_ms, "window_ms")?));
        if let Some(v) = refill_per_second {
            _body.insert("refill_per_second".to_string(), serde_json::json!(v));
        }
        if let Some(v) = cost {
            _body.insert("cost".to_string(), serde_json::json!(checked_int(v, "cost")?));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Read a schedule definition.
    #[wasm_bindgen(js_name = scheduleGet)]
    pub async fn schedule_get(&self, name: String) -> Result<JsValue, JsValue> {
        let path = format!("/v1/cron/schedules/{}", enc(&name));
        self.request("GET", path, None).await
    }

    /// Create/update a schedule. target = {kind: webhook|queue|grpc, ...}. Exactly one of cron / one_shot_at_ms.
    #[wasm_bindgen(js_name = scheduleUpsert)]
    pub async fn schedule_upsert(&self, name: String, target: JsValue, cron: Option<String>, one_shot_at_ms: Option<f64>, delivery: Option<String>, max_retries: Option<f64>) -> Result<JsValue, JsValue> {
        let path = format!("/v1/cron/schedules/{}", enc(&name));
        let mut _body = serde_json::Map::new();
        _body.insert("target".to_string(), serde_wasm_bindgen::from_value(target).map_err(|e| err(0, e.into()))?);
        if let Some(v) = cron {
            _body.insert("cron".to_string(), serde_json::json!(v));
        }
        if let Some(v) = one_shot_at_ms {
            _body.insert("one_shot_at_ms".to_string(), serde_json::json!(checked_int(v, "one_shot_at_ms")?));
        }
        if let Some(v) = delivery {
            _body.insert("delivery".to_string(), serde_json::json!(v));
        }
        if let Some(v) = max_retries {
            _body.insert("max_retries".to_string(), serde_json::json!(checked_int(v, "max_retries")?));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("PUT", path, Some(_payload)).await
    }

    /// Record a fire; duplicate fire_id is deduped (exactly-once).
    #[wasm_bindgen(js_name = scheduleRecordRun)]
    pub async fn schedule_record_run(&self, name: String, fire_id: String, fired_at_ms: Option<f64>) -> Result<JsValue, JsValue> {
        let path = format!("/v1/cron/schedules/{}/runs", enc(&name));
        let mut _body = serde_json::Map::new();
        _body.insert("fire_id".to_string(), serde_json::Value::String(fire_id));
        if let Some(v) = fired_at_ms {
            _body.insert("fired_at_ms".to_string(), serde_json::json!(checked_int(v, "fired_at_ms")?));
        }
        let _payload = serde_json::to_string(&serde_json::Value::Object(_body)).unwrap();
        self.request("POST", path, Some(_payload)).await
    }

    /// Recent run history.
    #[wasm_bindgen(js_name = scheduleHistory)]
    pub async fn schedule_history(&self, name: String) -> Result<JsValue, JsValue> {
        let path = format!("/v1/cron/schedules/{}/history", enc(&name));
        self.request("GET", path, None).await
    }
}
