// GENERATED by generate.py from operations.json, with compatibility helpers
// preserved during merge resolution.
// Fiducia client (TypeScript). Zero runtime deps (global fetch).

// Shared payload/error contract; type-only, no runtime cost.
export type {
  KvEntry,
  KvGetResponse,
  Leadership,
  LockGrant,
  ProposeError,
  ProposeOutcome,
  ServiceInstance,
  ServiceListResponse,
} from "@fiducia/interfaces/typescript";

export interface WatchEvent<T = any> {
  event: string;
  data: T;
  id?: string;
}

export class FiduciaError extends Error {
  constructor(public status: number, public body: any) {
    super(`fiducia: HTTP ${status}`);
  }
}

const enc = encodeURIComponent;

export class FiduciaClient {
  constructor(private base: string, private timeout = 30000) {
    this.base = base.replace(/\/+$/, "");
  }

  private async request(method: string, path: string, body?: any): Promise<any> {
    const ctl = new AbortController();
    const t = setTimeout(() => ctl.abort(), this.timeout);
    try {
      const r = await fetch(this.base + path, {
        method,
        signal: ctl.signal,
        headers: body !== undefined ? { "content-type": "application/json" } : {},
        body: body !== undefined ? JSON.stringify(body) : undefined,
      });
      const text = await r.text();
      const parsed = text ? JSON.parse(text) : null;
      if (!r.ok) throw new FiduciaError(r.status, parsed);
      return parsed;
    } finally {
      clearTimeout(t);
    }
  }

  private async *watch(path: string): AsyncGenerator<WatchEvent> {
    const res = await fetch(this.base + path, {
      method: "GET",
      headers: { accept: "text/event-stream" },
    });
    if (!res.ok) {
      const text = await res.text();
      const data = text ? JSON.parse(text) : null;
      throw new FiduciaError(res.status, data);
    }
    if (!res.body?.getReader) throw new Error("fiducia: response body is not streamable");

    const reader = res.body.getReader();
    const decoder = new TextDecoder();
    let buffer = "";
    try {
      for (;;) {
        const { value, done } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        let boundary = buffer.indexOf("\n\n");
        while (boundary >= 0) {
          const block = buffer.slice(0, boundary);
          buffer = buffer.slice(boundary + 2);
          const event = parseSseBlock(block);
          if (event) yield event;
          boundary = buffer.indexOf("\n\n");
        }
      }
      buffer += decoder.decode();
      const event = parseSseBlock(buffer);
      if (event) yield event;
    } finally {
      reader.releaseLock();
    }
  }

  async health(): Promise<any> {
    return this.request("GET", "/healthz");
  }

  async status(): Promise<any> {
    return this.request("GET", "/v1/status");
  }

  async lockGet(key: string): Promise<any> {
    return this.request("GET", `/v1/locks?key=${enc(key)}`);
  }

  async lockAcquire(
    key: string,
    opts: { holder?: string; ttl_ms?: number; wait?: boolean } = {},
  ): Promise<any> {
    return this.request("POST", "/v1/locks/acquire", {
      key,
      holder: opts.holder,
      ttl_ms: opts.ttl_ms,
      wait: opts.wait,
    });
  }

  async lockAcquireMany(
    keys: string[],
    opts: { holder?: string; ttl_ms?: number; wait?: boolean } = {},
  ): Promise<any> {
    return this.request("POST", "/v1/locks/acquire", {
      keys,
      holder: opts.holder,
      ttl_ms: opts.ttl_ms,
      wait: opts.wait,
    });
  }

  async lockRelease(holder: string, fencingToken: number): Promise<any> {
    return this.request("POST", "/v1/locks/release", { holder, fencing_token: fencingToken });
  }

  async semaphoreGet(key: string): Promise<any> {
    return this.request("GET", `/v1/semaphores?key=${enc(key)}`);
  }

  async semaphoreAcquire(
    key: string,
    limit: number,
    opts: { holder?: string; ttl_ms?: number; wait?: boolean } = {},
  ): Promise<any> {
    return this.request("POST", "/v1/semaphores/acquire", {
      key,
      limit,
      holder: opts.holder,
      ttl_ms: opts.ttl_ms,
      wait: opts.wait,
    });
  }

  async semaphoreRelease(key: string, holder: string, fencingToken: number): Promise<any> {
    return this.request("POST", "/v1/semaphores/release", { key, holder, fencing_token: fencingToken });
  }

  async kvGet(key: string): Promise<any> {
    return this.request("GET", `/v1/kv?key=${enc(key)}`);
  }

  async kvPut(
    key: string,
    value: string,
    opts: { ttl_ms?: number; prev_revision?: number } = {},
  ): Promise<any> {
    return this.request("PUT", `/v1/kv?key=${enc(key)}`, {
      value,
      ttl_ms: opts.ttl_ms,
      prev_revision: opts.prev_revision,
    });
  }

  async kvDelete(key: string): Promise<any> {
    return this.request("DELETE", `/v1/kv?key=${enc(key)}`);
  }

  async kvList(prefix: string): Promise<any> {
    return this.request("GET", `/v1/kv?prefix=${enc(prefix)}`);
  }

  kvWatch(key: string): AsyncGenerator<WatchEvent> {
    return this.watch(`/v1/kv?key=${enc(key)}&watch=true`);
  }

  kvWatchPrefix(prefix: string): AsyncGenerator<WatchEvent> {
    return this.watch(`/v1/kv?prefix=${enc(prefix)}&watch=true`);
  }

  async electionGet(name: string): Promise<any> {
    return this.request("GET", `/v1/elections/${enc(name)}`);
  }

  async electionCampaign(name: string, candidate: string, ttlMs: number): Promise<any> {
    return this.request("POST", `/v1/elections/${enc(name)}/campaign`, {
      candidate,
      ttl_ms: ttlMs,
    });
  }

  async electionRenew(name: string, candidate: string, fencingToken: number): Promise<any> {
    return this.request("POST", `/v1/elections/${enc(name)}/renew`, {
      candidate,
      fencing_token: fencingToken,
    });
  }

  async electionResign(name: string, candidate: string, fencingToken: number): Promise<any> {
    return this.request("POST", `/v1/elections/${enc(name)}/resign`, {
      candidate,
      fencing_token: fencingToken,
    });
  }

  electionWatch(name: string): AsyncGenerator<WatchEvent> {
    return this.watch(`/v1/elections/${enc(name)}/watch`);
  }

  async serviceInstances(service: string): Promise<any> {
    return this.request("GET", `/v1/services/${enc(service)}`);
  }

  async serviceRegister(
    service: string,
    instanceId: string,
    address: string,
    ttlMs: number,
    opts: { metadata?: Record<string, any> } = {},
  ): Promise<any> {
    return this.request("PUT", `/v1/services/${enc(service)}/instances/${enc(instanceId)}`, {
      address,
      ttl_ms: ttlMs,
      metadata: opts.metadata,
    });
  }

  async serviceHeartbeat(
    service: string,
    instanceId: string,
    opts: { ttl_ms?: number } = {},
  ): Promise<any> {
    return this.request("POST", `/v1/services/${enc(service)}/instances/${enc(instanceId)}/heartbeat`, {
      ttl_ms: opts.ttl_ms,
    });
  }

  async serviceDeregister(service: string, instanceId: string): Promise<any> {
    return this.request("DELETE", `/v1/services/${enc(service)}/instances/${enc(instanceId)}`);
  }

  async serviceList(): Promise<any> {
    return this.request("GET", "/v1/services");
  }

  serviceWatch(service: string): AsyncGenerator<WatchEvent> {
    return this.watch(`/v1/services/${enc(service)}/watch`);
  }

  async rateLimitGet(tenant: string, key: string): Promise<any> {
    return this.request("GET", `/v1/rate-limit/${enc(tenant)}/${enc(key)}`);
  }

  async rateLimitCheck(
    tenant: string,
    key: string,
    algorithm: string,
    limit: number,
    windowMs: number,
    opts: { refill_per_second?: number; cost?: number } = {},
  ): Promise<any> {
    return this.request("POST", `/v1/rate-limit/${enc(tenant)}/${enc(key)}/check`, {
      algorithm,
      limit,
      window_ms: windowMs,
      refill_per_second: opts.refill_per_second,
      cost: opts.cost,
    });
  }

  async scheduleGet(name: string): Promise<any> {
    return this.request("GET", `/v1/cron/schedules/${enc(name)}`);
  }

  async scheduleUpsert(
    name: string,
    target: Record<string, any>,
    opts: { cron?: string; one_shot_at_ms?: number; delivery?: string; max_retries?: number } = {},
  ): Promise<any> {
    return this.request("PUT", `/v1/cron/schedules/${enc(name)}`, {
      target,
      cron: opts.cron,
      one_shot_at_ms: opts.one_shot_at_ms,
      delivery: opts.delivery,
      max_retries: opts.max_retries,
    });
  }

  async scheduleRecordRun(name: string, fireId: string, opts: { fired_at_ms?: number } = {}): Promise<any> {
    return this.request("POST", `/v1/cron/schedules/${enc(name)}/runs`, {
      fire_id: fireId,
      fired_at_ms: opts.fired_at_ms,
    });
  }

  async scheduleHistory(name: string): Promise<any> {
    return this.request("GET", `/v1/cron/schedules/${enc(name)}/history`);
  }
}

function parseSseBlock(block: string): WatchEvent | undefined {
  let event = "message";
  let id: string | undefined;
  const data: string[] = [];
  for (const rawLine of block.replace(/\r\n/g, "\n").split("\n")) {
    if (!rawLine || rawLine.startsWith(":")) continue;
    const colon = rawLine.indexOf(":");
    const field = colon >= 0 ? rawLine.slice(0, colon) : rawLine;
    let value = colon >= 0 ? rawLine.slice(colon + 1) : "";
    if (value.startsWith(" ")) value = value.slice(1);
    if (field === "event") event = value;
    if (field === "id") id = value;
    if (field === "data") data.push(value);
  }
  if (!data.length) return undefined;
  const raw = data.join("\n");
  let decoded: any = raw;
  try {
    decoded = JSON.parse(raw);
  } catch {
    decoded = raw;
  }
  return { event, id, data: decoded };
}
