// GENERATED by generate.py from operations.json — DO NOT EDIT BY HAND.
// Fiducia client (TypeScript) — generated. Zero runtime deps (global fetch).
export class FiduciaError extends Error {
  constructor(public status: number, public body: any) { super(`fiducia: HTTP ${status}`); }
}
const enc = encodeURIComponent;
export class FiduciaClient {
  constructor(private base: string, private timeout = 30000) { this.base = base.replace(/\/$/, ""); }
  private async request(method: string, path: string, body?: any): Promise<any> {
    const ctl = new AbortController();
    const t = setTimeout(() => ctl.abort(), this.timeout);
    try {
      const r = await fetch(this.base + path, {
        method, signal: ctl.signal,
        headers: body !== undefined ? { "content-type": "application/json" } : {},
        body: body !== undefined ? JSON.stringify(body) : undefined,
      });
      const text = await r.text();
      const parsed = text ? JSON.parse(text) : null;
      if (!r.ok) throw new FiduciaError(r.status, parsed);
      return parsed;
    } finally { clearTimeout(t); }
  }

  async health(): Promise<any> {
    return this.request("GET", `/healthz`);
  }

  async status(): Promise<any> {
    return this.request("GET", `/v1/status`);
  }

  async lockGet(key: string): Promise<any> {
    return this.request("GET", `/v1/locks?key=${enc(key)}`);
  }

  async lockAcquire(key: string, opts: { holder?: string; ttl_ms?: number; wait?: boolean } = {}): Promise<any> {
    return this.request("POST", `/v1/locks/acquire`, { key: key, holder: opts.holder, ttl_ms: opts.ttl_ms, wait: opts.wait });
  }

  async lockAcquireMany(keys: string[], opts: { holder?: string; ttl_ms?: number; wait?: boolean } = {}): Promise<any> {
    return this.request("POST", `/v1/locks/acquire`, { keys: keys, holder: opts.holder, ttl_ms: opts.ttl_ms, wait: opts.wait });
  }

  async lockRelease(holder: string, fencingToken: number): Promise<any> {
    return this.request("POST", `/v1/locks/release`, { holder: holder, fencing_token: fencingToken });
  }

  async semaphoreGet(key: string): Promise<any> {
    return this.request("GET", `/v1/semaphores?key=${enc(key)}`);
  }

  async semaphoreAcquire(key: string, limit: number, opts: { holder?: string; ttl_ms?: number; wait?: boolean } = {}): Promise<any> {
    return this.request("POST", `/v1/semaphores/acquire`, { key: key, limit: limit, holder: opts.holder, ttl_ms: opts.ttl_ms, wait: opts.wait });
  }

  async semaphoreRelease(key: string, holder: string, fencingToken: number): Promise<any> {
    return this.request("POST", `/v1/semaphores/release`, { key: key, holder: holder, fencing_token: fencingToken });
  }

  async kvGet(key: string): Promise<any> {
    return this.request("GET", `/v1/kv?key=${enc(key)}`);
  }

  async kvPut(key: string, value: string, opts: { ttl_ms?: number; prev_revision?: number } = {}): Promise<any> {
    return this.request("PUT", `/v1/kv?key=${enc(key)}`, { value: value, ttl_ms: opts.ttl_ms, prev_revision: opts.prev_revision });
  }

  async kvDelete(key: string): Promise<any> {
    return this.request("DELETE", `/v1/kv?key=${enc(key)}`);
  }

  async electionGet(name: string): Promise<any> {
    return this.request("GET", `/v1/elections/${enc(name)}`);
  }

  async electionCampaign(name: string, candidate: string, ttlMs: number): Promise<any> {
    return this.request("POST", `/v1/elections/${enc(name)}/campaign`, { candidate: candidate, ttl_ms: ttlMs });
  }

  async electionRenew(name: string, candidate: string, fencingToken: number): Promise<any> {
    return this.request("POST", `/v1/elections/${enc(name)}/renew`, { candidate: candidate, fencing_token: fencingToken });
  }

  async electionResign(name: string, candidate: string, fencingToken: number): Promise<any> {
    return this.request("POST", `/v1/elections/${enc(name)}/resign`, { candidate: candidate, fencing_token: fencingToken });
  }

  async serviceInstances(service: string): Promise<any> {
    return this.request("GET", `/v1/services/${enc(service)}`);
  }

  async serviceRegister(service: string, instanceId: string, address: string, ttlMs: number, opts: { metadata?: Record<string, any> } = {}): Promise<any> {
    return this.request("PUT", `/v1/services/${enc(service)}/instances/${enc(instanceId)}`, { address: address, ttl_ms: ttlMs, metadata: opts.metadata });
  }

  async serviceHeartbeat(service: string, instanceId: string, opts: { ttl_ms?: number } = {}): Promise<any> {
    return this.request("POST", `/v1/services/${enc(service)}/instances/${enc(instanceId)}/heartbeat`, { ttl_ms: opts.ttl_ms });
  }

  async serviceDeregister(service: string, instanceId: string): Promise<any> {
    return this.request("DELETE", `/v1/services/${enc(service)}/instances/${enc(instanceId)}`);
  }

  async rateLimitGet(tenant: string, key: string): Promise<any> {
    return this.request("GET", `/v1/rate-limit/${enc(tenant)}/${enc(key)}`);
  }

  async rateLimitCheck(tenant: string, key: string, algorithm: string, limit: number, windowMs: number, opts: { refill_per_second?: number; cost?: number } = {}): Promise<any> {
    return this.request("POST", `/v1/rate-limit/${enc(tenant)}/${enc(key)}/check`, { algorithm: algorithm, limit: limit, window_ms: windowMs, refill_per_second: opts.refill_per_second, cost: opts.cost });
  }

  async scheduleGet(name: string): Promise<any> {
    return this.request("GET", `/v1/cron/schedules/${enc(name)}`);
  }

  async scheduleUpsert(name: string, target: Record<string, any>, opts: { cron?: string; one_shot_at_ms?: number; delivery?: string; max_retries?: number } = {}): Promise<any> {
    return this.request("PUT", `/v1/cron/schedules/${enc(name)}`, { target: target, cron: opts.cron, one_shot_at_ms: opts.one_shot_at_ms, delivery: opts.delivery, max_retries: opts.max_retries });
  }

  async scheduleRecordRun(name: string, fireId: string, opts: { fired_at_ms?: number } = {}): Promise<any> {
    return this.request("POST", `/v1/cron/schedules/${enc(name)}/runs`, { fire_id: fireId, fired_at_ms: opts.fired_at_ms });
  }

  async scheduleHistory(name: string): Promise<any> {
    return this.request("GET", `/v1/cron/schedules/${enc(name)}/history`);
  }
}
