// GENERATED by generate.py from operations.json — DO NOT EDIT BY HAND.
// Fiducia client (TypeScript) — generated. Zero runtime deps (global fetch).
export class FiduciaError extends Error {
  constructor(public status: number, public body: any) { super(`fiducia: HTTP ${status}`); }
}
const enc = encodeURIComponent;
export class FiduciaClient {
  constructor(private base: string, private timeout = 30000) { this.base = base.replace(/\/$/, ""); }
  private async request(method: string, path: string, body?: any): Promise<any> {
    const ctl = new AbortController();
    const t = setTimeout(() => ctl.abort(), this.timeout);
    try {
      const r = await fetch(this.base + path, {
        method, signal: ctl.signal,
        headers: body !== undefined ? { "content-type": "application/json" } : {},
        body: body !== undefined ? JSON.stringify(body) : undefined,
      });
      const text = await r.text();
      const parsed = text ? JSON.parse(text) : null;
      if (!r.ok) throw new FiduciaError(r.status, parsed);
      return parsed;
    } finally { clearTimeout(t); }
  }

  async health(): Promise<any> {
    return this.request("GET", `/healthz`);
  }

  async status(): Promise<any> {
    return this.request("GET", `/v1/status`);
  }

  async lockGet(key: string): Promise<any> {
    return this.request("GET", `/v1/locks?key=${enc(key)}`);
  }

  async lockAcquire(key: string, opts: { holder?: string; ttl_ms?: number; wait?: boolean } = {}): Promise<any> {
    return this.request("POST", `/v1/locks/acquire`, { key: key, holder: opts.holder, ttl_ms: opts.ttl_ms, wait: opts.wait });
  }

  async lockAcquireMany(keys: string[], opts: { holder?: string; ttl_ms?: number; wait?: boolean } = {}): Promise<any> {
    return this.request("POST", `/v1/locks/acquire`, { keys: keys, holder: opts.holder, ttl_ms: opts.ttl_ms, wait: opts.wait });
  }

  async lockRelease(holder: string, fencingToken: number): Promise<any> {
    return this.request("POST", `/v1/locks/release`, { holder: holder, fencing_token: fencingToken });
  }

  async semaphoreGet(key: string): Promise<any> {
    return this.request("GET", `/v1/semaphores?key=${enc(key)}`);
  }

  async semaphoreAcquire(key: string, limit: number, opts: { holder?: string; ttl_ms?: number; wait?: boolean } = {}): Promise<any> {
    return this.request("POST", `/v1/semaphores/acquire`, { key: key, limit: limit, holder: opts.holder, ttl_ms: opts.ttl_ms, wait: opts.wait });
  }

  async semaphoreRelease(key: string, holder: string, fencingToken: number): Promise<any> {
    return this.request("POST", `/v1/semaphores/release`, { key: key, holder: holder, fencing_token: fencingToken });
  }

  async idempotencyGet(key: string): Promise<any> {
    return this.request("GET", `/v1/idempotency?key=${enc(key)}`);
  }

  async idempotencyClaim(key: string, opts: { owner?: string; ttl_ms?: number; ttl?: string; metadata?: Record<string, any> } = {}): Promise<any> {
    return this.request("POST", `/v1/idempotency/claim`, { key: key, owner: opts.owner, ttl_ms: opts.ttl_ms, ttl: opts.ttl, metadata: opts.metadata });
  }

  async idempotencyComplete(key: string, owner: string, fencingToken: number, opts: { result?: Record<string, any> } = {}): Promise<any> {
    return this.request("POST", `/v1/idempotency/complete`, { key: key, owner: owner, fencing_token: fencingToken, result: opts.result });
  }

  async kvGet(key: string): Promise<any> {
    return this.request("GET", `/v1/kv?key=${enc(key)}`);
  }

  async kvPut(key: string, value: string, opts: { ttl_ms?: number; prev_revision?: number } = {}): Promise<any> {
    return this.request("PUT", `/v1/kv?key=${enc(key)}`, { value: value, ttl_ms: opts.ttl_ms, prev_revision: opts.prev_revision });
  }

  async kvDelete(key: string): Promise<any> {
    return this.request("DELETE", `/v1/kv?key=${enc(key)}`);
  }

  async counterGet(key: string): Promise<any> {
    return this.request("GET", `/v1/counters?key=${enc(key)}`);
  }

  async counterAdd(key: string, delta: number, opts: { prev_revision?: number } = {}): Promise<any> {
    return this.request("POST", `/v1/counters/add`, { key: key, delta: delta, prev_revision: opts.prev_revision });
  }

  async counterSet(key: string, value: number, opts: { prev_revision?: number } = {}): Promise<any> {
    return this.request("POST", `/v1/counters/set`, { key: key, value: value, prev_revision: opts.prev_revision });
  }

  async barrierGet(name: string): Promise<any> {
    return this.request("GET", `/v1/barriers?name=${enc(name)}`);
  }

  async barrierCreate(name: string, policy: Record<string, any>, opts: { expected?: number; deadline_ms?: number } = {}): Promise<any> {
    return this.request("POST", `/v1/barriers/create`, { name: name, policy: policy, expected: opts.expected, deadline_ms: opts.deadline_ms });
  }

  async barrierArrive(name: string, participant: string, opts: { weight?: number; veto?: boolean } = {}): Promise<any> {
    return this.request("POST", `/v1/barriers/arrive`, { name: name, participant: participant, weight: opts.weight, veto: opts.veto });
  }

  async taskGet(name: string): Promise<any> {
    return this.request("GET", `/v1/tasks?name=${enc(name)}`);
  }

  async taskCreate(name: string, taskType: string, opts: { payload?: Record<string, any>; deadline_ms?: number } = {}): Promise<any> {
    return this.request("POST", `/v1/tasks/create`, { name: name, task_type: taskType, payload: opts.payload, deadline_ms: opts.deadline_ms });
  }

  async taskClaim(name: string, worker: string, opts: { ttl_ms?: number } = {}): Promise<any> {
    return this.request("POST", `/v1/tasks/claim`, { name: name, worker: worker, ttl_ms: opts.ttl_ms });
  }

  async taskProgress(name: string, worker: string, fencingToken: number, opts: { percent?: number; checkpoint?: Record<string, any> } = {}): Promise<any> {
    return this.request("POST", `/v1/tasks/progress`, { name: name, worker: worker, fencing_token: fencingToken, percent: opts.percent, checkpoint: opts.checkpoint });
  }

  async taskComplete(name: string, worker: string, fencingToken: number, opts: { result?: Record<string, any> } = {}): Promise<any> {
    return this.request("POST", `/v1/tasks/complete`, { name: name, worker: worker, fencing_token: fencingToken, result: opts.result });
  }

  async taskFail(name: string, worker: string, fencingToken: number, opts: { retryable?: boolean } = {}): Promise<any> {
    return this.request("POST", `/v1/tasks/fail`, { name: name, worker: worker, fencing_token: fencingToken, retryable: opts.retryable });
  }

  async taskCancel(name: string): Promise<any> {
    return this.request("POST", `/v1/tasks/cancel`, { name: name });
  }

  async effectGet(name: string): Promise<any> {
    return this.request("GET", `/v1/effects?name=${enc(name)}`);
  }

  async effectPrepare(name: string, effectType: string, idempotencyKey: string, opts: { payload?: Record<string, any>; risk?: string; required_approvals?: number } = {}): Promise<any> {
    return this.request("POST", `/v1/effects/prepare`, { name: name, effect_type: effectType, payload: opts.payload, risk: opts.risk, idempotency_key: idempotencyKey, required_approvals: opts.required_approvals });
  }

  async effectApprove(name: string, principal: string): Promise<any> {
    return this.request("POST", `/v1/effects/approve`, { name: name, principal: principal });
  }

  async effectCommit(name: string, opts: { result?: Record<string, any> } = {}): Promise<any> {
    return this.request("POST", `/v1/effects/commit`, { name: name, result: opts.result });
  }

  async effectAbort(name: string): Promise<any> {
    return this.request("POST", `/v1/effects/abort`, { name: name });
  }

  async handoffGet(name: string): Promise<any> {
    return this.request("GET", `/v1/handoffs?name=${enc(name)}`);
  }

  async handoffOffer(name: string, resource: string, from: string, to: string, fromToken: number, opts: { context?: Record<string, any>; ttl_ms?: number } = {}): Promise<any> {
    return this.request("POST", `/v1/handoffs/offer`, { name: name, resource: resource, from: from, to: to, from_token: fromToken, context: opts.context, ttl_ms: opts.ttl_ms });
  }

  async handoffAccept(name: string, to: string): Promise<any> {
    return this.request("POST", `/v1/handoffs/accept`, { name: name, to: to });
  }

  async handoffReject(name: string, to: string): Promise<any> {
    return this.request("POST", `/v1/handoffs/reject`, { name: name, to: to });
  }

  async decisionGet(name: string): Promise<any> {
    return this.request("GET", `/v1/decisions?name=${enc(name)}`);
  }

  async decisionPropose(name: string, question: string, options: Record<string, any>, policy: Record<string, any>, opts: { deadline_ms?: number } = {}): Promise<any> {
    return this.request("POST", `/v1/decisions/propose`, { name: name, question: question, options: options, policy: policy, deadline_ms: opts.deadline_ms });
  }

  async decisionVote(name: string, voter: string, opts: { option?: string; confidence?: number; weight?: number; veto?: boolean; evidence?: Record<string, any> } = {}): Promise<any> {
    return this.request("POST", `/v1/decisions/vote`, { name: name, voter: voter, option: opts.option, confidence: opts.confidence, weight: opts.weight, veto: opts.veto, evidence: opts.evidence });
  }

  async budgetGet(name: string): Promise<any> {
    return this.request("GET", `/v1/budgets?name=${enc(name)}`);
  }

  async budgetSet(name: string, limit: Record<string, any>): Promise<any> {
    return this.request("POST", `/v1/budgets/set`, { name: name, limit: limit });
  }

  async budgetReserve(name: string, reservationId: string, holder: string, amount: Record<string, any>): Promise<any> {
    return this.request("POST", `/v1/budgets/reserve`, { name: name, reservation_id: reservationId, holder: holder, amount: amount });
  }

  async budgetCommit(name: string, reservationId: string, actual: Record<string, any>): Promise<any> {
    return this.request("POST", `/v1/budgets/commit`, { name: name, reservation_id: reservationId, actual: actual });
  }

  async budgetRelease(name: string, reservationId: string): Promise<any> {
    return this.request("POST", `/v1/budgets/release`, { name: name, reservation_id: reservationId });
  }

  async electionGet(name: string): Promise<any> {
    return this.request("GET", `/v1/elections/${enc(name)}`);
  }

  async electionCampaign(name: string, candidate: string, ttlMs: number, opts: { metadata?: Record<string, any> } = {}): Promise<any> {
    return this.request("POST", `/v1/elections/${enc(name)}/campaign`, { candidate: candidate, ttl_ms: ttlMs, metadata: opts.metadata });
  }

  async electionRenew(name: string, candidate: string, fencingToken: number): Promise<any> {
    return this.request("POST", `/v1/elections/${enc(name)}/renew`, { candidate: candidate, fencing_token: fencingToken });
  }

  async electionResign(name: string, candidate: string, fencingToken: number): Promise<any> {
    return this.request("POST", `/v1/elections/${enc(name)}/resign`, { candidate: candidate, fencing_token: fencingToken });
  }

  async serviceInstances(service: string, opts: { metadata?: Record<string, any> } = {}): Promise<any> {
    return this.request("GET", `/v1/services/${enc(service)}?metadata=${enc(metadata)}`);
  }

  async serviceRegister(service: string, instanceId: string, address: string, ttlMs: number, opts: { metadata?: Record<string, any> } = {}): Promise<any> {
    return this.request("PUT", `/v1/services/${enc(service)}/instances/${enc(instanceId)}`, { address: address, ttl_ms: ttlMs, metadata: opts.metadata });
  }

  async serviceHeartbeat(service: string, instanceId: string, opts: { ttl_ms?: number } = {}): Promise<any> {
    return this.request("POST", `/v1/services/${enc(service)}/instances/${enc(instanceId)}/heartbeat`, { ttl_ms: opts.ttl_ms });
  }

  async serviceDeregister(service: string, instanceId: string): Promise<any> {
    return this.request("DELETE", `/v1/services/${enc(service)}/instances/${enc(instanceId)}`);
  }

  async rateLimitGet(tenant: string, key: string): Promise<any> {
    return this.request("GET", `/v1/rate-limit/${enc(tenant)}/${enc(key)}`);
  }

  async rateLimitCheck(tenant: string, key: string, algorithm: string, limit: number, windowMs: number, opts: { refill_per_second?: number; cost?: number } = {}): Promise<any> {
    return this.request("POST", `/v1/rate-limit/${enc(tenant)}/${enc(key)}/check`, { algorithm: algorithm, limit: limit, window_ms: windowMs, refill_per_second: opts.refill_per_second, cost: opts.cost });
  }

  async scheduleGet(name: string): Promise<any> {
    return this.request("GET", `/v1/cron/schedules/${enc(name)}`);
  }

  async scheduleUpsert(name: string, target: Record<string, any>, opts: { cron?: string; one_shot_at_ms?: number; delivery?: string; max_retries?: number } = {}): Promise<any> {
    return this.request("PUT", `/v1/cron/schedules/${enc(name)}`, { target: target, cron: opts.cron, one_shot_at_ms: opts.one_shot_at_ms, delivery: opts.delivery, max_retries: opts.max_retries });
  }

  async scheduleRecordRun(name: string, fireId: string, opts: { fired_at_ms?: number } = {}): Promise<any> {
    return this.request("POST", `/v1/cron/schedules/${enc(name)}/runs`, { fire_id: fireId, fired_at_ms: opts.fired_at_ms });
  }

  async scheduleHistory(name: string): Promise<any> {
    return this.request("GET", `/v1/cron/schedules/${enc(name)}/history`);
  }
}
